<?php


namespace app\agent\controller;

use app\BaseController;

//需要验证

class Base extends BaseController
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

}