<?php

namespace app\agent\controller;

use app\common\model\MoneyLog as models;
use app\common\model\PayRecharge;
use app\common\model\PayCash;
use app\common\model\FanyongLog;
use app\common\service\Excel;
use app\common\model\UserModel;

class MoneyLog extends Base
{
    protected $uid;//代理用户ID
    protected $agent = [];//代理下级ID
    protected $page;//当前页
    protected $limit;//每页显示数量
    protected $post = [];//查询搜索条件
    /**
     * 资金流动控制器
     */
    public function initialize()
    {
        $info = session('agent_info');
        $this->uid = $info['uid'];
        if(!empty($info['agent'])){
            array_push($info['agent'],$info['uid']);
            $this->agent = $info['agent'];
        }
        $this->page = $this->request->post('page', 1);
        $this->limit = $this->request->post('limit', 10);
        $this->post = $this->request->post();
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 代理查看资金记录
     */
    public function getFund(){
        $arr = $this->verify();//验证参数
        $order = 'a.id desc';
        isset($this->post['create_time_sort']) && $order = 'a.id ' . $this->post['create_time_sort'];
        $model = new models();
        $list = $model->page_list($arr['map'], $this->limit, $this->page, $order);
        return $this->success($list);
    }

    /**
     * 用户充值记录
     */
    public function userRecharge(){
        $arr = $this->verify();//验证参数
        $model = new PayRecharge();
        $list = $model->page_list($arr['map'], $this->limit, $this->page, $arr['date']);
        return $this->success($list);
    }

    /**
     * 用户提现记录
     */
    public function userWithdrawal(){
        $arr = $this->verify(3);//验证参数
        $model = new PayCash();
        $list = $model->page_list($arr['map'], $this->limit, $this->page, $arr['date']);
        return $this->success($list);
    }

    /**
     * 用户推广记录
     */
    public function userPromotion(){
        $arr = $this->verify(2);//验证参数
        $model = new FanyongLog();
        $list = $model->page_list($arr['map'], $this->limit, $this->page, $arr['date']);
        return $this->success($list);
    }

    /**
     * 验证参数
     * @param int $type
     * @return array[]
     */
    private function verify($type = 1){
        if($type == 1){
            $uid = 'uid';
            $user = 'a.uid';
        }else if($type == 2){
            $uid = 'user_id';
            $user = 'a.user_id';
        }else{
            $uid = 'u_id';
            $user = 'a.u_id';
        }
        $map = $date = [];
        isset($this->post['status']) && $this->post['status'] != '' && $map[] = ['a.status', '=', $this->post['status']];
        isset($this->post['type']) && $this->post['type'] != '' && $map[] = ['a.type', '=', intval($this->post['type'])];
        isset($this->post['class']) && $this->post['class'] != '' && $map[] = ['a.class', '=', $this->post['class']];
        isset($this->post['user_name']) && $this->post['user_name'] != '' && $map[] = ['b.user_name|b.phone', 'like', '%' . $this->post['user_name'] . '%'];
        isset($this->post['agents']) && $this->post['agents'] != '' && $map[] = ['b.market_uid', '=', $this->post['agents']];
        isset($this->post['order_on']) && $this->post['order_on'] != '' && $map[] = ['a.order_on', '=', $this->post['order_on']];
        isset($this->post[$uid]) && $this->post[$uid] != '' && $map[] = [$user, '=', $this->post[$uid]];
        if (isset($this->post['start']) && isset($this->post['end'])) {
            $date['start'] = $this->post['start'];
            $date['end'] = $this->post['end'];
        }
        if(!empty($this->agent)){
            $map[] = [$uid,'in',$this->agent];
        }else{
            $map[] = [$uid,'=',$this->uid];
        }
        return $arr = array(
            'map' => $map,
            'date' => $date,
        );
    }

    public function payCash(){
        //当前页
        $page = $this->request->param('page', 1);
        //每页显示数量
        $limit = $this->request->param('limit', 20);
        $is_excel = $this->request->param('is_excel', 0);

        $ids = $this->request->param('ids');

        //查询搜索条件
        $post = $this->request->param();
        $map=[];
        $date=[];
        isset($post['user_name']) && $map [] = ['b.user_name|b.phone', 'like', '%' . $post['user_name'] . '%'];
        isset($post['status'])&& $post['status']!='' && $map [] = ['a.status', '=',intval($post['status'])];
        isset($post['type']) && $map [] = ['a.type', '=',intval($post['type'])];
        isset($post['agents']) && $post['agents']!='' && $map[]= ['b.market_uid', '=',$post['agents']];
        isset($post['uid']) && $post['uid']!='' && $map[]= ['a.u_id', '=',$post['uid']];
        isset($post['order_on']) && $post['order_on']!='' && $map[]= ['a.order_on', '=',$post['order_on']];
        isset($post['pay_type']) && $post['pay_type']!='' && $map[]= ['a.pay_type', '=',$post['pay_type']];
        if (isset($post['start']) && isset($post['end'])) {
            $date['start'] = $post['start'];
            $date['end'] = $post['end'];
        }
        $model = new PayCash();
        $list = $model->page_list($map,$limit, $page,$date);

        if ($is_excel >0){
            $map = [];
            if($ids == ''){
                $ids = '0';
            }
            $ids = explode(',', $ids);
            $map[] = ['a.id', 'in', $ids];

            $list = $model->page_list($map, count($ids), 1, []);
            $list = $list->toArray();
            if (!empty($list['data'])){
                $this->excel($list['data']);
            }
        }
        return $this->success($list);
    }

    private function excel($data){
        $excel = new Excel();

        $field_title = [
//            'id'=>'ID',
//            'create_time'=>'申请时间',
//            'success_time'=>'审核时间',
            'money'=>'提现金额',
//            'money_before'=>'开始金额',
//            'money_end'=>'结束金额',
//            'money_fee'=>'手续费',
//            'money_actual'=>'实际到账金额',
//            'order_on'=>'订单号',
//            'phone'=>'电话',
            'user_name'=>'姓名',
//            'u_bank_name'=>'银行名',
            'u_back_card'=>'收款账号',
            'u_back_user_name'=>'收款名',
//            'msg'=>'备注',
        ];
        $fields = [
//            'id',
//            'create_time',
//            'success_time',
//            'success_time',
            'money',
//            'money_before',
//            'money_end',
//            'money_fee',
//            'money_actual',
//            'order_on',
//            'phone',
            'user_name',
//            'u_bank_name',
            'u_back_card',
            'u_back_user_name',
//            'msg'
        ];
        $filename = '提现导出'.date('YmdHis');
        return  $excel->export($field_title,$fields,$data,$filename);
    }

    public function belowAgents(){
        $model = new UserModel();
        $subList = $this->allSubordinate($model,$this->uid);
        dd($subList);
    }

    private function allSubordinate($model,$user){
        $arr = $where = array();
        if(is_array($user)){
            $where[] = ['agent_id','in',$user];
        }else{
            $where[] = ['agent_id','=',$user];
        }
        $res = $model->where($where)->select()->toArray();
        if(!empty($res)){
            $arr = array_column($res,'id');
        }
        return array_merge($user, $this->allSubordinate($model,$arr));
    }
}