<?php


namespace app\admin\controller\notice;


use app\admin\controller\Base;
use app\common\model\InvitationModel as models;
use app\common\traites\PublicCrudTrait;
use think\exception\ValidateException;
use \app\validate\Invitation as validates;

class Invitation extends Base
{
    protected $model;
    use PublicCrudTrait;

    /**
     * 公告控制器
     */
    public function initialize()
    {
        $this->model = new models();
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 列表
     */
    public function index()
    {
        $page = $this->request->post('page', 1);
        $limit = $this->request->post('limit', 10);
        $list = $this->model->page_list($limit, $page);
        return $this->success($list);
    }

    /**
     * 添加
     */
    public function add()
    {
        //过滤数据
        $postField = 'title,number,reward';
        $post = $this->request->only(explode(',', $postField), 'post', null);

        //验证数据
        try {
            validate(validates::class)->scene('add')->check($post);
        } catch (ValidateException $e) {
            // 验证失败 输出错误信息
            return $this->failed($e->getError());
        }

        $user = $this->model->where('title', $post['title'])->find();
        if ($user) return $this->failed('该奖励已存在');
        $post['status'] = isset($post['status']) ? $post['status'] : 1;//默认正常状态
        $post['admin_uid'] = session('admin_user.id');//管理员ID
        $save = $this->model->save($post);
        if ($save) return $this->success([]);
        return $this->failed('新增失败');
    }



    /**
     * 修改
     * @return mixed
     */
    public function edit()
    {
        //过滤数据
        $postField = 'id,title,number,reward';
        $post = $this->request->only(explode(',', $postField), 'post', null);

        //验证数据
        try {
            validate(validates::class)->scene('edit')->check($post);
        } catch (ValidateException $e) {
            // 验证失败 输出错误信息
            return $this->failed($e->getError());
        }

        //查询是否重复的该菜单
        $find = $this->model->where('title', $post['title'])->where('id', '<>', $post['id'])->find();
        if ($find) return $this->failed('该奖励已存在');

        //执行修改数据
        $save = $this->model->update($post);
        if ($save) return $this->success([]);
        return $this->failed('修改失败');
    }

    /**
     * 状态修改
     * @return mixed|\think\response\Json
     */
    public function statusEdit(){
        //过滤数据
        $postField = 'id,status';
        $post = $this->request->only(explode(',', $postField), 'post', null);

        //验证数据
        try {
            validate(validates::class)->scene('status')->check($post);
        } catch (ValidateException $e) {
            // 验证失败 输出错误信息
            return $this->failed($e->getError());
        }

        //查询是否重复的该菜单
        $find = $this->model->where('id', $post['id'])->find();
        if (!$find) return $this->failed('该奖励不存在');

        //执行修改数据
        $save = $this->model->update($post);
        if ($save) return $this->success([]);
        return $this->failed('修改失败');
    }
}