<?php

namespace app\admin\controller;

use app\common\model\UserModel;
use app\common\model\WaresOrderModel;
use app\validate\Order as validates;
use think\exception\ValidateException;

class Exchange extends Base
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
    /**
     * 兑换列表
     * @return mixed
     */
    public function index()
    {
        //当前页
        $page = $this->request->post('page', 1);
        //每页显示数量
        $limit = $this->request->post('limit', 10);
        //查询搜索条件
        $post = array_filter($this->request->post());
        $map = [];
        isset($post['wares_no']) && $map [] = ['a.wares_no', 'like', '%' . $post['wares_no'] . '%'];
        isset($post['wares_name']) && $map [] = ['b.wares_name', 'like', '%' . $post['wares_name'] . '%'];
        isset($post['uid']) && $map [] = ['a.uid', '=',$post['uid']];

        if (isset($post['user_name']) && !empty($post['user_name'])){
            $find = UserModel::where('user_name',$post['user_name'])->find();
            if (!empty($find)){
                $map [] = ['a.uid', '=',$find->id];
            }
        }
        isset($post['id']) && $map [] = ['a.id', '=', $post['id']];

        $list = WaresOrderModel::page_list($map, $limit, $page,'id desc','a.*,b.wares_name');
        return $this->success($list);
    }

    /**
     * 订单状态修改
     * @return mixed|null
     */
    public function edit()
    {
        //过滤数据
        $postField = 'status,id';
        $post = $this->request->only(explode(',', $postField), 'post', null);
        $post = array_filter($post);

        //验证数据
        try {
            validate(validates::class)->scene('edit')->check($post);
        } catch (ValidateException $e) {
            // 验证失败 输出错误信息
            return $this->failed($e->getError());
        }

        //执行修改数据
        $save = WaresOrderModel::update($post);
        if ($save) return $this->success([]);
        return $this->failed('修改失败');
    }
}