<?php

namespace app\admin\controller;


use app\common\model\AdminModel as models;
use app\common\model\Goods;
use app\common\model\GoodsOrder;
use app\common\model\HomeTokenModel;
use app\common\model\OrderModel;
use app\common\model\PayCash;
use app\common\model\PayRecharge;
use app\common\model\UserModel;
use app\common\traites\PublicCrudTrait;
use app\validate\Admin;
use think\exception\ValidateException;
use think\facade\Db;

class Index extends Base
{
    protected $model;
    use PublicCrudTrait;
    /**
     * 后台用户控制器
     */
    public function initialize()
    {
        $this->model = new models();
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    //获取列表信息
    public function index()
    {
        //当前页
        $page = $this->request->post('page', 1);
        //每页显示数量
        $limit = $this->request->post('limit', 10);
        //查询搜索条件
        $post= array_filter($this->request->post());
        $map=[];
        isset($post['user_name']) && $map [] = ['a.user_name', 'like', '%' . $post['user_name'] . '%'];
        isset($post['role']) && $map [] = ['role','=',$post['role']];
        isset($post['market_level']) && $map [] = ['a.market_level','=',$post['market_level']];

        $list = $this->model->page_list($map,$limit, $page);
        return $this->success($list);
    }

    public function add()
    {
        //过滤数据
        $postField = 'pid,user_name,pwd,role,market_level,remarks,invitation_code,operate_pwd';
        $post = $this->request->only(explode(',', $postField), 'post', null);

        //验证数据
        try {
            validate(Admin::class)->scene('add')->check($post);
        } catch (ValidateException $e) {
            // 验证失败 输出错误信息
            return $this->failed($e->getError());
        }

        //验证成功，查询是否存在该用户
        $user = $this->model->where('user_name', $post['user_name'])->find();
        if ($user) return $this->failed('该用户以存在');
        //加密密码
        $post['pwd'] = !empty($post['pwd']) && isset($post['pwd']) ? pwdEncryption($post['pwd']) : pwdEncryption(admin_Initial_pwd());
        $post['invitation_code'] =generateCode(32,40);
        $post['operate_pwd'] = !empty($post['operate_pwd']) && isset($post['operate_pwd']) ? pwdEncryption($post['operate_pwd']) : pwdEncryption(admin_Initial_pwd());
        //插入数据库
        !isset($post['pid']) && $post['pid'] = 0;
        !isset($post['market_level']) && $post['market_level'] = 0;
        $save = false;
        Db::startTrans();
        try {
            //写入角色 并
           $this->model->save($post);
//            $this->market(intval($this->model->id), intval($post['pid']),intval($post['market_level']));
            $save = true;
            // 提交事务
            Db::commit();
        } catch (\Exception $e) {
            // 回滚事务
            Db::rollback();
        }
        if ($save) return $this->success([]);
        return $this->failed('新增失败');
    }

    //写入到 common_market_relation 数据
    public function market(int $userId, int $pid,int $level)
    {
        if ($userId <= 0) return false;
        $db = Db::name('common_market_relation');
        if ($pid >= 1) {
            //查询到当前用户的父级
            $find = $db->where('aid', $pid)->find();
            //获取用户父级信息 插入到数据
            $db->insert(['aid' => $userId, 'a_level' => $level, 'pid' => $find['aid'], 'p_level' => $find['a_level'], 'path' => $find['path'] . ',' . $userId]);
            return true;
        }
        // 新增当前数据
        $db->insert(['aid' => $userId, 'a_level' => $level, 'pid' => 0, 'p_level' => 0, 'path' => $userId]);
        return true;
    }

    /**
     * 获取用户信息
     * @return mixed
     */
    public function detail()
    {
        //过滤数据
        $postField = 'id';
        $post = $this->request->only(explode(',', $postField), 'post', null);
        //验证数据
        try {
            validate(Admin::class)->scene('detail')->check($post);
        } catch (ValidateException $e) {
            // 验证失败 输出错误信息
            return $this->failed($e->getError());
        }
        //查询用户数据
        $user = $this->model->find($post['id']);
        if ($user) return $this->success($user);
        return $this->failed('用户不存在');
    }

    /**
     * 修改方法
     * @return mixed
     */
    public function edit()
    {
        //过滤数据
        $postField = 'id,user_name,pwd,role,market_level,remarks,operate_pwd';
        $post = $this->request->only(explode(',', $postField), 'post', null);

        //验证数据
        try {
            validate(Admin::class)->scene('edit')->check($post);
        } catch (ValidateException $e) {
            // 验证失败 输出错误信息
            return $this->failed($e->getError());
        }

        //查询是否重复的用户名
        $find = $this->model->where('user_name', $post['user_name'])->where('id', '<>', $post['id'])->find();
        //if ($find) return $this->failed('用户已存在');
        !empty($post['pwd']) && $post['pwd'] = pwdEncryption($post['pwd']);
        !empty($post['operate_pwd']) && $post['operate_pwd'] = pwdEncryption($post['operate_pwd']);
        $post=array_filter($post);
        //执行修改数据
        $save = $this->model->update($post);

        if ($save) return $this->success([]);
        return $this->failed('修改失败');
    }
     /**
     * 统计
     * */
    public function statistics(){
        $map = [];
        // 增加 代理商 推广列表
          if (session('admin_user.role')==2) $map = ['b.market_uid' => session('admin_user.id')];
        $array=array();
        $today=date('Y-m-d');//今天
        $yesterday=date('Y-m-d',strtotime('-1 day'));//昨天
        $tomorrow=date('Y-m-d',strtotime('+1 day'));//明天
        //平台总利润 usdt/本地
        $PayRecharge=new PayRecharge();

        //总充值笔数
        $array['total_recharger_num']=$PayRecharge->alias('a')->join('common_user b', 'a.uid = b.id', 'left')->where($map)->where('a.status',1)->count('a.id');
        //今日充值笔数
        $array['today_recharger_num']=$PayRecharge->alias('a')->join('common_user b', 'a.uid = b.id', 'left')->where($map)->where('a.status',1)->whereBetweenTime('success_time',$today,$tomorrow)->count('a.id');
        //昨日充值笔数
        //$array['yesterday_recharger_num']=$PayRecharge->alias('a')->join('common_user b', 'a.uid = b.id', 'left')->where($map)->where('a.status',1)->whereBetweenTime('success_time',$yesterday,$today)->count('a.id');
        //总充值金额
        $array['total_recharger_ben_money'] = $PayRecharge->where('status',2)->sum('money');
        $array['today_recharger_ben_money'] = $PayRecharge->where('status',2)->whereTime('success_time','today')->sum('money');
        $array['recharger_man']= $PayRecharge->where($map)->where('status',2)->group('uid')->count();

        $PayCash=new PayCash();
        //提现
        $array['total_cash_num'] = $PayCash->where('status',1)->count();
        $array['today_cash_num'] = $PayCash->where('status',1)->whereTime('success_time','today')->count();
        $array['total_cash_ben_money'] = $PayCash->where('status',1)->sum('money');
        $array['today_cash_ben_money'] = $PayCash->where('status',1)->whereTime('success_time','today')->sum('money');

//        $total_Recharge_ben=$PayRecharge->alias('a')->join('common_user b', 'a.uid = b.id', 'left')->where($map)->where('a.type',1)->where('a.status',1)->sum('a.money');//本地
//        $total_Recharge_usdt= $PayRecharge->alias('a')->join('common_user b', 'a.uid = b.id', 'left')->where($map)->where('a.type',2)->where('a.status',1)->sum('a.money');//usdt
//        $total_Cash_ben=$PayCash->alias('a')->join('common_user b', 'a.uid = b.id', 'left')->where($map)->where('a.type',1)->where('a.status',1)->sum('a.money');//本地
//        $total_Cash_usdt= $PayCash->alias('a')->join('common_user b', 'a.uid = b.id', 'left')->where($map)->where('a.type',2)->where('a.status',1)->sum('money');//usdt
//        $array['total_ben_profit']=$total_Recharge_ben-$total_Cash_ben;
//        $array['total_usdt_profit']=$total_Recharge_usdt-$total_Cash_usdt;
//        //今天利润 usdt/本地
//        $today_Recharge_ben=$PayRecharge->alias('a')->join('common_user b', 'a.uid = b.id', 'left')->where($map)->where('a.type',1)->where('a.status',1)->whereBetweenTime('success_time',$today,$tomorrow)->sum('a.money');//本地
//        $today_Recharge_usdt= $PayRecharge->alias('a')->join('common_user b', 'a.uid = b.id', 'left')->where($map)->where('a.type',2)->where('a.status',1)->whereBetweenTime('success_time',$today,$tomorrow)->sum('a.money');//usdt
//        $today_Cash_ben=$PayCash->alias('a')->join('common_user b', 'a.uid = b.id', 'left')->where($map)->where('a.type',1)->where('a.status',1)->whereBetweenTime('success_time',$today,$tomorrow)->sum('a.money');//本地
//        $today_Cash_usdt= $PayCash->alias('a')->join('common_user b', 'a.uid = b.id', 'left')->where($map)->where('a.type',2)->where('a.status',1)->whereBetweenTime('success_time',$today,$tomorrow)->sum('a.money');//usdt
//        $array['today_ben_profit']=$today_Recharge_ben-$today_Cash_ben;
//        $array['today_usdt_profit']=$today_Recharge_usdt-$today_Cash_usdt;
//        //昨天利润 usdt/本地
//        $yesterday_Recharge_ben=$PayRecharge->alias('a')->join('common_user b', 'a.uid = b.id', 'left')->where($map)->where('a.type',1)->where('a.status',1)->whereBetweenTime('success_time',$yesterday,$today)->sum('money');//本地
//        $yesterday_Recharge_usdt= $PayRecharge->alias('a')->join('common_user b', 'a.uid = b.id', 'left')->where($map)->where('a.type',2)->where('a.status',1)->whereBetweenTime('success_time',$yesterday,$today)->sum('money');//usdt
//        $yesterday_Cash_ben=$PayCash->alias('a')->join('common_user b', 'a.uid = b.id', 'left')->where($map)->where('a.type',1)->where('a.status',1)->whereBetweenTime('success_time',$yesterday,$today)->sum('money');//本地
//        $yesterday_Cash_usdt= $PayCash->alias('a')->join('common_user b', 'a.uid = b.id', 'left')->where($map)->where('a.type',2)->where('a.status',1)->whereBetweenTime('success_time',$yesterday,$today)->sum('money');//usdt
//        $array['yesterday_ben_profit']=$yesterday_Recharge_ben-$yesterday_Cash_ben;
//        $array['yesterday_usdt_profit']=$yesterday_Recharge_usdt-$yesterday_Cash_usdt;

        //总注册量
        $User= new UserModel();
        $array['total_register']=$User->alias('b')->where($map)->count('id');
        //今日注册
        $array['today_register']=$User->alias('b')->where($map)->whereBetweenTime('create_time',$today,$tomorrow)->count('id');
        //昨天注册
        $array['yesterday_register']=$User->alias('b')->where($map)->whereBetweenTime('create_time',$yesterday,$today)->count('id');


        $OrderModel = new GoodsOrder();
        //总购买产品数量
        $array['total_product_num']=$OrderModel->where($map)->count();
         //今日购买产品数量
        $array['today_product_num']=$OrderModel->where($map)->whereBetweenTime('create_time',$today,$tomorrow)->count();


        $array['total_product_ben_money']=$OrderModel->where($map)->sum('order_money');
        //今日购买产品数量
        $array['today_product_ben_money']=$OrderModel->where($map)->whereBetweenTime('create_time',$today,$tomorrow)->sum('order_money');


//        //总充值金额 usdt/本地
//        $array['total_recharger_ben_money']=$total_Recharge_ben;
//        $array['total_recharger_usdt_money']=$total_Recharge_usdt;
//        //今天充值金额 usdt/本地
//        $array['today_recharger_ben_money']=$today_Recharge_ben;
//        $array['today_recharger_usdt_money']=$today_Recharge_usdt;
//        //昨天充值金额 usdt/本地
//        $array['yesterday_recharger_ben_money']=$yesterday_Recharge_ben;
//        $array['yesterday_recharger_usdt_money']=$yesterday_Recharge_usdt;
//
//
//        //总提现笔数
//        $array['total_cash_num']=$PayCash->alias('a')->join('common_user b', 'a.uid = b.id', 'left')->where($map)->where('a.status',1)->count('a.id');
//        //今日提现笔数
//        $array['today_cash_num']=$PayCash->alias('a')->join('common_user b', 'a.uid = b.id', 'left')->where($map)->where('a.status',1)->whereBetweenTime('success_time',$today,$tomorrow)->count('a.id');
//        //昨日提现笔数
//        $array['yesterday_cash_num']=$PayCash->alias('a')->join('common_user b', 'a.uid = b.id', 'left')->where($map)->where('a.status',1)->whereBetweenTime('success_time',$yesterday,$today)->count('a.id');
//
//
//        //总提现金额 usdt/本地
//        $array['total_cash_ben_money']=$total_Cash_ben;
//        $array['total_cash_usdt_money']=$total_Cash_usdt;
//        //今天提现金额 usdt/本地
//        $array['today_cash_ben_money']=$today_Cash_ben;
//        $array['today_cash_usdt_money']=$today_Cash_usdt;
//        //昨天提现金额 usdt/本地
//        $array['yesterday_ben_money']=$yesterday_Cash_ben;
//        $array['yesterday_usdt_money']=$yesterday_Cash_usdt;
//
//        //充值人数
//        $array['recharger_man']= Db::name('common_pay_recharge')->alias('a')->join('common_user b', 'a.uid = b.id', 'left')->where($map)->where('a.status',1)->group('a.uid')->count('a.id');
//        //充值率
//         if ($array['recharger_man']==0 ||$array['total_register']==0){
//           $array['recharger_rate']=0;
//          }else{
//           $array['recharger_rate']=round(($array['recharger_man']/$array['total_register']),2)*100;
//          }
//        //复充人数
//        $array['recharging_man']=Db::name('common_pay_recharge')->alias('a')->join('common_user b', 'a.uid = b.id', 'left')->where($map)->where('a.status',1)->group('a.uid')->having('count(a.uid) > 1')->count('a.id');
//        //复充率
//        if ($array['recharging_man']==0 ||$array['recharger_man']==0){
//            $array['recharging_rate']=0;
//        }else{
//            $array['recharging_rate']=round(($array['recharging_man']/$array['recharger_man']),2)*100;
//        }
//        $TouziProductOrder=new \app\common\model\TouziProductOrder();
//        //总购买产品数量
//        $array['total_product_num']=$TouziProductOrder->alias('a')->join('common_user b', 'a.user_id = b.id', 'left')->where($map)->count('a.id');
//        //今日购买产品数量
//        $array['today_product_num']=$TouziProductOrder->alias('a')->join('common_user b', 'a.user_id = b.id', 'left')->where($map)->whereBetweenTime('a.create_time',$today,$tomorrow)->count('a.id');
//        //昨日购买产品数量
//        $array['yesterday_product_num']=$TouziProductOrder->alias('a')->join('common_user b', 'a.user_id = b.id', 'left')->where($map)->whereBetweenTime('a.create_time',$yesterday,$today)->count('a.id');
//
//           //总购买金额 本地
//        $array['total_product_ben_money']=$TouziProductOrder->alias('a')->join('common_user b', 'a.user_id = b.id', 'left')->where(['a.type'=>1])->where($map)->sum('a.buy_price_local');
//        $array['total_product_usdt_money']=$TouziProductOrder->alias('a')->join('common_user b', 'a.user_id = b.id', 'left')->where(['a.type'=>2])->where($map)->sum('a.buy_price_local');
//        //今日购买金额
//        $array['today_product_ben_money']=$TouziProductOrder->alias('a')->join('common_user b', 'a.user_id = b.id', 'left')->where(['a.type'=>1])->where($map)->whereBetweenTime('a.create_time',$today,$tomorrow)->sum('a.buy_price_local');
//        $array['today_product_usdt_money']=$TouziProductOrder->alias('a')->join('common_user b', 'a.user_id = b.id', 'left')->where(['a.type'=>2])->where($map)->whereBetweenTime('a.create_time',$today,$tomorrow)->sum('a.buy_price_local');
//        //昨日购买金额
//        $array['yesterday_product_ben_money']=$TouziProductOrder->alias('a')->join('common_user b', 'a.user_id = b.id', 'left')->where(['a.type'=>1])->where($map)->whereBetweenTime('a.create_time',$yesterday,$today)->sum('a.buy_price_local');
//        $array['yesterday_product_usdt_money']=$TouziProductOrder->alias('a')->join('common_user b', 'a.user_id = b.id', 'left')->where(['a.type'=>2])->where($map)->whereBetweenTime('a.create_time',$yesterday,$today)->sum('a.buy_price_local');

        //在线人数
        $array['dangqianzaixianrenshu']= HomeTokenModel::whereTime('create_time','-2 hours')->count();
        return $this->success($array);
    }
    
    public function Statistics_2(){


    }
}