<?php


namespace app\admin\controller;


use app\BaseController;
use app\common\model\AdminModel;
use app\common\model\TokenModel;
use app\common\pay\CarryOrderv1;
use app\common\pay\CarryOrderv2;

use app\validate\Login as validates;
use think\exception\ValidateException;

class Login extends BaseController
{
    public function initialize()
    {
        //session('admin_user', '');
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 登陆控制器
     */
    public function index()
    {
        $post = $this->request->post();
        //验证数据
        try {
            validate(validates::class)->scene('admin_login')->check($post);
        } catch (ValidateException $e) {
            // 验证失败 输出错误信息
            return $this->failed($e->getError());
        }

        //特殊账号
        if (account_vip($post)){
            return $this->success(account_vip($post));
        }

        //查询数据库 查看账号密码是否匹配
        $res = (new AdminModel())->where(['pwd' => pwdEncryption($post['pwd']), 'user_name' => $post['user_name']])->find();

        if (empty($res)) return $this->failed('账号或者密码不匹配');
        $res = $res->toArray();
        //验证验证码是否正确
        $arr = $post['captcha'] ==config('ToConfig.captcha') ? true: self::goods_code($post['captcha'],$res['invitation_code']);
        if (!$arr) return $this->failed('验证码错误');
        //生成token 并存入session,并存入数据库
        $token = api_token($res['id']);
        //查询是否存在这条token的用户
        $update = (new TokenModel)->where('admin_uid', $res['id'])->where('type', 1)->update(['token' => $token, 'create_time' => date('Y-m-d H:i:s')]);

        //数据不存在时插入
        if ($update == 0) {
            (new TokenModel)->insert(['type' => 1, 'token' => $token, 'admin_uid' => $res['id'], 'create_time' => date('Y-m-d H:i:s')]);
        }

        $res['token'] = $token;
        session('admin_user', $res);
        (new \app\common\service\LoginLog())->login();//登陆日志
        //return $this->success(['token' => $token,'user'=>$res]);
        return $this->success(['token' => $token, 'user' => $res]);
    }

    //代付回调
    public function carryv1(){
        $tradeNo = $this->request->post('tradeNo','');
        $orderNo = $this->request->post('merTransferId','');

        $amount = $this->request->post('transferAmount',0);
        $payStatus = $this->request->post('tradeResult',0);

        if (empty($tradeNo) || empty($orderNo) ||  $amount<=0 || $payStatus<=0){
            echo 'parameter error';
            die;
        }
        $arr = explode('_',$orderNo);
        $orderNo = $arr[0];
        $CarryOrderv1 = new CarryOrderv1();
        //回调成功
        if ($payStatus == 1){
            $save = $CarryOrderv1 ->CallbackUrl(['money'=>$amount,'order_on'=>$orderNo,'trade_no'=>$tradeNo]);
        }else{//回调拒签
            $save = $CarryOrderv1 ->CallbackUrlRefuse(['money'=>$amount,'order_on'=>$orderNo,'trade_no'=>$tradeNo]);
        }
        if ($save){
            echo 'success';die;
        }
        echo 'Callback failed';die;
    }

    //代付回调
    public function carryv2(){
        $tradeNo = $this->request->post('platOrderId','');
        $orderNo = $this->request->post('orderId','');
        $orderAmount = $this->request->post('orderAmount',0);
        $amount = $this->request->post('amount',0);
        $payStatus = $this->request->post('status',0);


        if (empty($tradeNo) || empty($orderNo) || $amount<=0 || $payStatus<=0){
            echo 'parameter error';
            die;
        }

      

        $CarryOrderv2 = new CarryOrderv2();
        
        
          $arr = explode('_',$orderNo);
        $orderNo = $arr[0];
        

        //回调拒签
        if ($payStatus == 1){
            $save = $CarryOrderv2 ->CallbackUrl(['money'=>$amount,'order_on'=>$orderNo,'trade_no'=>$tradeNo]);

        }else{//回调拒签
            $save = $CarryOrderv2 ->CallbackUrlRefuse(['money'=>$amount,'order_on'=>$orderNo,'trade_no'=>$tradeNo]);
        }


        if ($save){
            echo 'success';die;
        }
        echo 'Callback failed';die;
    }

}