<?php

/**
 * 产品
 *
 * */
namespace app\admin\controller;
use app\common\model\TouziProduct as models;
use app\common\traites\PublicCrudTrait;
use app\validate\TouziProduct as validates;
use think\exception\ValidateException;

class TouziProduct extends Base
{
    protected $model;
    use PublicCrudTrait;

    public function initialize()
    {
        $this->model =new models();
        parent::initialize(); // TODO: Change the autogenerated stub
    }
    /**
     *
     * 产品列表
     * */
    public function index(){
        //当前页
        $page = $this->request->post('page', 1);
        //每页显示数量
        $limit = $this->request->post('limit', 10);
        //查询搜索条件
        $post = $this->request->post();
        $map =[];
        isset($post['is_open'])&& $map[]= ['is_open','=',$post['is_open']];
        $order = 'create_time desc';
        $map[]= ['del','=',0];
        $list =$this->model->page_list($map,$limit,$page,$order);

        return $this->success($list);
    }
    /**
     * 新增
     * */
    public function add(){
        //过滤数据
        $postField = 'level_id,level_id_text,validity_period,title,title_en,gain_hour,gain_all,gain_day,buy_price_usdt,buy_price_local,pic_path,is_open,progress_rate,product_describe';
        $post = $this->request->only(explode(',', $postField), 'post', null);
        //验证数据
        try {
            validate(validates::class)->scene('add')->check($post);
        } catch (ValidateException $e) {
            // 验证失败 输出错误信息
            return $this->failed($e->getError());
        }
        //查询是否重复
        $find = $this->model->where('level_id',$post['level_id'])->where('class',$post['class'])->where('del',0)->find();
        if ($find) return $this->failed($find);
        //执行修改数据
        $post['admin_uid']=session('admin_user.id');
        $post['create_time']=date('Y-m-d H:i:s');
        $save = $this->model->save($post);
        if ($save) return $this->success([]);
        return $this->failed('添加失败');
    }
    /**
     * 编辑
     * */
    public function edit(){
        //过滤数据
        $postField = 'id,level_id,level_id_text,validity_period,title,title_en,gain_hour,gain_all,gain_day,buy_price_usdt,buy_price_local,pic_path,is_open,progress_rate,product_describe';
        $post = $this->request->only(explode(',', $postField), 'post', null);
        //验证数据
        try {
            validate(validates::class)->scene('edit')->check($post);
        } catch (ValidateException $e) {
            // 验证失败 输出错误信息
            return $this->failed($e->getError());
        }
        //检测
        $find = $this->model->where('id', $post['id'])->find();
        if (!$find) return $this->failed('产品不存在');
        //执行修改数据
        $save = $this->model->update($post);
        if ($save) return $this->success([]);
        return $this->failed('修改失败');
    }
    /**
     * 删除
     * */
    public function del(){
        //过滤数据
        $postField ='id';
        $post = $this->request->only(explode(',', $postField), 'post', null);
        //验证数据
        try {
            validate(validates::class)->scene('del')->check($post);
        } catch (ValidateException $e) {
            // 验证失败 输出错误信息
            return $this->failed($e->getError());
        }
        //检测
        $find = $this->model->where('id', $post['id'])->find();
        if (!$find) return $this->failed('产品不存在');
        //检测是否有订单
        $TouziProductOrder=new \app\common\model\TouziProductOrder();
        $res_order=$TouziProductOrder->where('product_id',$post['id'])->where('order_status',0)->where('end_time','<',date('Y-m-d H:i:s'))->find();
        if ($res_order){
            return $this->failed('当前产品还有订单存在,不能删除');
        }
        $post['del']=1;
        //执行修改数据
        $save = $this->model->update($post);
        if ($save) return $this->success([]);
        return $this->failed('删除失败');
    }
}