<?php


namespace app\admin\controller;


use app\common\model\TouziKefu as models;
use app\common\traites\PublicCrudTrait;
use app\validate\TouziKefu as validates;
use think\exception\ValidateException;

class TouziKefu extends Base
{
    protected $model;
    use PublicCrudTrait;

    public function initialize()
    {
        $this->model =new models();
        parent::initialize(); // TODO: Change the autogenerated stub
    }
    /**
     *
     * 列表
     * */
    public function index(){
        //当前页
        $page = $this->request->post('page', 1);
        //每页显示数量
        $limit = $this->request->post('limit', 10);
        //查询搜索条件
        $post = array_filter($this->request->post());
        $map =[];
        $order = 'id desc';
        $list =$this->model->page_list($map,$limit,$page,$order);

        return $this->success($list);
    }

    /**
     * 添加
     * */
    public function add(){
        //过滤数据
        $postField = 'url,remarks,type,phone,username,address,market_uid';
        $post = $this->request->only(explode(',', $postField), 'post', null);
        //验证数据
        try {
            validate(validates::class)->scene('add')->check($post);
        } catch (ValidateException $e) {
            // 验证失败 输出错误信息
            return $this->failed($e->getError());
        }
        $save = $this->model->save($post);
        if ($save) return $this->success([]);
        return $this->failed('添加失败');
    }
    /**
     * 编辑
     * */
    public function edit(){
        //过滤数据
        $postField = 'url,remarks,id,type,phone,username,address,market_uid';
        $post = $this->request->only(explode(',', $postField), 'post', null);
        //验证数据
        try {
            validate(validates::class)->scene('edit')->check($post);
        } catch (ValidateException $e) {
            // 验证失败 输出错误信息
            return $this->failed($e->getError());
        }
        //检测
        $find = $this->model->where('id', $post['id'])->find();
        if (!$find) return $this->failed('数据不存在');
        //执行修改数据
        $save = $this->model->update($post);
        if ($save) return $this->success([]);
        return $this->failed('修改失败');
    }
    /**
     * 删除
     * */
    public function del(){
        //过滤数据
        $postField = 'id';
        $post = $this->request->only(explode(',', $postField), 'post', null);
        //验证数据
        try {
            validate(validates::class)->scene('del')->check($post);
        } catch (ValidateException $e) {
            // 验证失败 输出错误信息
            return $this->failed($e->getError());
        }
        //检测
        $find = $this->model->where('id', $post['id'])->find();
        if (!$find) return $this->failed('数据不存在');
        //执行修改数据
        $save = $this->model->where('id', $post['id'])->delete();
        if ($save) return $this->success([]);
        return $this->failed('删除失败');
    }
}