<?php

/**
 * 产品订单
 * */
namespace app\admin\controller;

use app\common\model\GoodsOrder as models;
use app\common\traites\PublicCrudTrait;

class TouziProductOrder  extends Base
{
    protected $model;
    use PublicCrudTrait;

    public function initialize()
    {
        $this->model =new models();
        parent::initialize(); // TODO: Change the autogenerated stub
    }
    //获取列表信息
    public function index()
    {
        //当前页
        $page = $this->request->post('page', 1);
        //每页显示数量
        $limit = $this->request->post('limit', 10);
        //查询搜索条件
        $post =$this->request->post();
        $map = $date = [];
        isset($post['order_no']) && $map [] = ['a.order_no', 'like', '%' . $post['order_no'] . '%'];
        isset($post['goods_name']) && $map [] = ['a.goods_name', 'like', '%' . $post['goods_name'] . '%'];
        isset($post['uname']) && $map [] = ['a.uname', '=',$post['uname']];
        isset($post['uid']) && $map [] = ['a.uid', '=', $post['uid']];
        if (isset($post['start']) && isset($post['end'])) {
            $date['start'] = $post['start'];
            $date['end'] = $post['end'];
        }

        $list = $this->model->page_list($map, $limit, $page, $date);
        return $this->success($list);
    }
}