<?php


namespace app\admin\controller;

/**
 *
 * 轮播图
 * */
use app\common\model\Ads as models;
use app\common\traites\PublicCrudTrait;
use app\validate\TouziAds as validates;
use think\exception\ValidateException;

class TouziAds extends Base
{
    protected $model;
    use PublicCrudTrait;

    public function initialize()
    {
        $this->model =new models();
        parent::initialize(); // TODO: Change the autogenerated stub
    }
    /**
     *
     * 首页
     * */
    public function index(){
        //当前页
        $page = $this->request->post('page', 1);
        //每页显示数量
        $limit = $this->request->post('limit', 10);
        //查询搜索条件
        $post = array_filter($this->request->post());
        $map =[];
        $order = 'sort asc';
        $list =$this->model->page_list($map,$limit,$page,$order);
        return $this->success($list);
    }
    /**
     * 添加
     * */
    public function add(){
        //过滤数据
        $postField = 'img,sort,status,type,is_type,content';
        $post = $this->request->only(explode(',', $postField), 'post', null);
        //验证数据
        try {
            validate(validates::class)->scene('add')->check($post);
        } catch (ValidateException $e) {
            // 验证失败 输出错误信息
            return $this->failed($e->getError());
        }
        if (isset($post['img']) && is_array($post['img']))$post['img'] = $post['img'][0];
        $post['add_time']=date('Y-m-d H:i:s');
        $save = $this->model->save($post);
        if ($save) return $this->success([]);
        return $this->failed('添加失败');
    }
    /**
     * 编辑
     * */
    public function edit(){
        //过滤数据
        $postField = 'id,img,sort,status,type,is_type,content';
        $post = $this->request->only(explode(',', $postField), 'post', null);
        //验证数据
        try {
            validate(validates::class)->scene('edit')->check($post);
        } catch (ValidateException $e) {
            // 验证失败 输出错误信息
            return $this->failed($e->getError());
        }
        //检测
        $find = $this->model->where('id', $post['id'])->find();
        if (!$find) return $this->failed('数据不存在');
        if (isset($post['img']) && is_array($post['img']))$post['img'] = $post['img'][0];
        //执行修改数据
        $save = $this->model->update($post);
        if ($save) return $this->success([]);
        return $this->failed('修改失败');
    }
    /**
     * 删除
     * */
    public function del(){
        //过滤数据
        $postField = 'id';
        $post = $this->request->only(explode(',', $postField), 'post', null);
        //验证数据
        try {
            validate(validates::class)->scene('del')->check($post);
        } catch (ValidateException $e) {
            // 验证失败 输出错误信息
            return $this->failed($e->getError());
        }
        //检测
        $find = $this->model->where('id', $post['id'])->find();
        if (!$find) return $this->failed('数据不存在');
        $del=$this->model->where('id',$post['id'])->delete();
        if ($del) return $this->success([]);
        return $this->failed('删除失败');
    }
}