<?php


namespace app\admin\controller;

use app\common\model\TouziInvitation as models;
use app\common\traites\PublicCrudTrait;
use app\validate\TouziInvitation as validates;
use think\exception\ValidateException;

/**
 *
 * 邀请用户奖励设置
 * */
class Touzilnvitation extends Base
{
    protected $model;
    use PublicCrudTrait;

    public function initialize()
    {
        $this->model =new models();
        parent::initialize(); // TODO: Change the autogenerated stub
    }
    /**
     *
     * 奖励设置首页
     * */
    public function index(){
        //当前页
        $page = $this->request->post('page', 1);
        //每页显示数量
        $limit = $this->request->post('limit', 10);
        //查询搜索条件
        $post = array_filter($this->request->post());
        $map =[];
        $order = 'grade asc';
        $list =$this->model->page_list($map,$limit,$page,$order);
        return $this->success($list);
    }
    /**
     * 添加
     * */
    public function add(){
        //过滤数据
        $postField = 'title,number,reward,grade,status,type,content';
        $post = $this->request->only(explode(',', $postField), 'post', null);
        //验证数据
        try {
            validate(validates::class)->scene('add')->check($post);
        } catch (ValidateException $e) {
            // 验证失败 输出错误信息
            return $this->failed($e->getError());
        }
        $number=$this->model->where(['number'=>$post['number']])->find();
        if ($number){
            return $this->failed('您已经设置过相同人数的邀请奖励');
        }
        $post['admin_uid']=session('admin_user.id');
        $post['create_time']=date('Y-m-d H:i:s');
        //执行数据
        $save = $this->model->save($post);
        if ($save) return $this->success([]);
        return $this->failed('添加失败');
    }
    /**
     * 编辑
     * */
    public function edit()
    {
        //过滤数据
        $postField = 'id,title,number,reward,grade,status,content';
        $post = $this->request->only(explode(',', $postField), 'post', null);
        //验证数据
        try {
            validate(validates::class)->scene('edit')->check($post);
        } catch (ValidateException $e) {
            // 验证失败 输出错误信息
            return $this->failed($e->getError());
        }
        $number=$this->model->where('id','<>',$post['id'])->where('number',$post['number'])->find();
        if ($number){
            return $this->failed('已有相同邀请人数奖励');
        }
        //执行修改数据
        $save = $this->model->update($post);
        if ($save) return $this->success([]);
        return $this->failed('修改失败');
    }
    /**
     * 删除
     * */
    public function del(){

    }

}