<?php

namespace app\admin\controller;


use app\common\model\AdminModel;
use \app\common\model\MoneyLog;
use app\common\model\UserModel;
use app\common\model\UserModel as models;
use app\common\traites\PublicCrudTrait;
use app\common\model\FanyongLog;
use app\common\model\SendLog;
use app\common\model\BankModel;
use app\validate\User as validates;
use think\exception\ValidateException;
use think\facade\Db;

class User extends Base
{
    protected $model;
    use PublicCrudTrait;

    public function initialize()
    {
        $this->model = new models();
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    //获取列表信息
    public function index()
    {
        //当前页
        $page = $this->request->post('page', 1);
        //每页显示数量
        $limit = $this->request->post('limit', 10);
        //查询搜索条件
        $post = array_filter($this->request->post());
        $map = $date = [];
        isset($post['user_name']) && $map [] = ['b.user_name', 'like', '%' . $post['user_name'] . '%'];
        isset($post['phone']) && $map[] = ['b.phone', '=', $post['phone']];
        isset($post['market_uid']) && $map [] = ['b.market_uid', '=', $post['market_uid']];
        isset($post['user_team']) && $map [] = ['b.user_team', '=', $post['user_team']];
        isset($post['id']) && $map [] = ['b.id', '=', $post['id']];

        if (isset($post['start']) && isset($post['end'])) {
            $date['start'] = $post['start'];
            $date['end'] = $post['end'];
        }

        $list = $this->model->page_list($map, $limit, $page, $date);
        return $this->success($list);
    }

    /**
     * 获取代理信息
     * */
    public function agent_data()
    {
        $AdminModel = new AdminModel();
        $res = $AdminModel->field('id,user_name')->where('role', 2)->select();
        return $this->success($res);
    }

    //代理商个人信息
    public function agent()
    {
        //当前页
        $page = $this->request->post('page', 1);
        //每页显示数量
        $limit = $this->request->post('limit', 10);
        $list = $this->model->page_one($limit, $page);
        return $this->success($list);
    }

    public function add()
    {
        //过滤数据
        $postField = 'user_name,sfz,phone,pwd,withdraw_pwd,market_uid,agent_id';
        $post = $this->request->only(explode(',', $postField), 'post', null);

        if (!$post || empty($post['market_uid'])) return $this->failed('业务员ID错误或不存在');
        //验证数据
        try {
            validate(validates::class)->scene('add')->check($post);
        } catch (ValidateException $e) {
            // 验证失败 输出错误信息
            return $this->failed($e->getError());
        }
        //查询是否重复的用户名
        $find = $this->model->where('user_name', $post['user_name'])->whereOr('phone', $post['phone'])->whereOr('sfz', $post['sfz'])->find();
//        if ($find) return $this->failed('用户已存在');

        //加密密码
        $post['pwd'] = !empty($post['pwd']) && isset($post['pwd']) ? md5($post['pwd']) : home_Initial_pwd();

        if (!empty($post['withdraw_pwd'])) {
            $post['withdraw_pwd'] = base64_encode(123456);
        }

        if (isset($post['agent_id']) && $post['agent_id'] > 0) {
            //查询用户是否存在
            $agent_info = $this->model->where('id', $post['agent_id'])->find();
            if (empty($agent_info)) {
                return $this->failed('代理不存在');
            }
            $post['user_team'] = $agent_info['user_team'];
        } else {
            $post['user_team'] = UserTeam();
        }
        //获取ID
        $post['ip'] = $this->request->ip();
        //执行修改数据
        $save = $this->model->save($post);
        if ($save) return $this->success([]);
        return $this->failed('修改失败');
    }


    public function rand_code()
    {
        $rand = userzm(6);
        $qc = $this->model->where('invitation_code', $rand)->find();
        if ($qc) {
            $this->rand_code();
        } else {
            return $rand;
        }
    }

    /**
     * 修改方法
     * @return mixed
     */
    public function edit()
    {
        //过滤数据
        $postField = 'id,user_name,sfz,phone,pwd,withdraw_pwd,money_approve,market_uid,is_real_name';
        $post = $this->request->only(explode(',', $postField), 'post', null);

        //验证数据
        try {
            validate(validates::class)->scene('edit')->check($post);
        } catch (ValidateException $e) {
            // 验证失败 输出错误信息
            return $this->failed($e->getError());
        }

        if (!$post || empty($post['market_uid'])) return $this->failed('业务员ID错误或不存在');
        $is_real_name = $post['is_real_name'];
        $post = array_filter($post);
        //查询是否重复的用户名

//        $find = $this->model->whereOr('user_name', $post['user_name'])->whereOr('phone', $post['phone'])->whereOr('sfz', $post['sfz'])->find();

//        if ($find && $find['id'] <> intval($post['id'])) return $this->failed('用户已存在');
        //加密密码
        if (!empty($post['pwd'])) {
            $post['pwd'] = md5($post['pwd']);
        } else {
            unset($post['pwd']);
        }

        if (!empty($post['withdraw_pwd'])) {
            $post['withdraw_pwd'] = base64_encode($post['withdraw_pwd']);
        }
        $post['is_real_name'] = $is_real_name;
        //执行修改数据
        $save = $this->model->update($post);
        if ($save) return $this->success([]);
        return $this->failed('修改失败');
    }


    //判断业务员存不存在
    public function is_admin($post)
    {
        if (!isset($post['market_uid']) || empty($post['market_uid'])) return false;
        $admin = (new AdminModel())->find($post['market_uid']);
        if (!$admin) return false;
        return $post;
    }

    //修改虚拟账号
    public function is_status()
    {
        $id = $this->request->post('id', 0);
        if ($id <= 0) return $this->failed('用户不存在');
        $find = $this->model->find($id);
        $find->is_fictitious = $find->is_fictitious == 1 ? 0 : 1;
        $save = $find->save();
        if ($save) return $this->success([]);
        return $this->failed('修改失败');
    }

    /**
     * 状态切换 上下架
     */
    public function withdrawalstatus()
    {
        //过滤数据
        $postField = 'id,is_withdraw';
        $post = $this->request->only(explode(',', $postField), 'post', null);
        $id = $post['id'];
        $is_withdraw = $post['is_withdraw'];
        $find = $this->model->find($id);
        $save = $find->save(['is_withdraw' => $is_withdraw]);
        if ($save) return $this->success([]);
        return $this->failed('修改失败');
    }

    /**
     * money_change_type: 1增加;2:减少
     * uid: 20  用户id
     * change_money:  变化金额
     * money_status: 90个人总收益 11银行卡充值 12积分 13绿币 14个人佣金 15团队津贴 16碳票 17碳汇 18可提现余额 其他：冻结金额
     * @return void|null
     */
    public function money_edit()
    {
        $postField = 'money_change_type,change_money,uid,money_status';
        $post = $this->request->only(explode(',', $postField), 'post', null);
        $post = array_filter($post);
        //验证数据
        try {
            validate(validates::class)->scene('money')->check($post);
        } catch (ValidateException $e) {
            // 验证失败 输出错误信息
            return $this->failed($e->getError());
        }

        //查询当前用户的余额
        $find = $this->model->find($post['uid']);
        if (!$find) return $this->failed('用户不存在');

        $this->amount_edit($post,$find);
    }

    /**
     * 验证操作密码是否正确
     * @return mixed|null
     */
    public function operate(){
        $postField = 'operate_pwd';
        $post = $this->request->only(explode(',', $postField), 'post', null);
        $post = array_filter($post);
        //验证数据
        try {
            validate(validates::class)->scene('operate')->check($post);
        } catch (ValidateException $e) {
            // 验证失败 输出错误信息
            return $this->failed($e->getError());
        }
        //判断操作密码是否正确
        $operate_pwd = session('admin_user.operate_pwd');
        if(pwdEncryption($post['operate_pwd'])!=$operate_pwd){
            return $this->failed('操作密码错误');
        }
        return $this->success([]);
    }
    /**
     * 用户余额修改
     * @param $post //传入参数
     * @param $find //用户信息
     * @return mixed|null
     */
    private function amount_edit($post,$find){
        $balance = 0;
        $field = '';
        $status = 0;
        $str = '';
        switch ($post['money_status']){
            case 90://个人总收益
                $balance = $find->money_balance;
                $field = 'money_balance';
                $status = $post['money_change_type'] == 1 ? 217:218;
                $str = '个人总收益';
                break;
            case 11://银行卡充值
                $balance = $find->money_purchase;
                $field = 'money_purchase';
                $status = $post['money_change_type'] == 1 ? 219:220;
                $str = '银行卡充值';
                break;
            case 12://积分
                $balance = $find->money_integral;
                $field = 'money_integral';
                $status = $post['money_change_type'] == 1 ? 221:222;
                $str = '积分';
                break;
            case 13://绿币
                $balance = $find->money_green;
                $field = 'money_green';
                $status = $post['money_change_type'] == 1 ? 223:224;
                $str = '绿币';
                break;
            case 14://个人佣金
                $balance = $find->money_hire;
                $field = 'money_hire';
                $status = $post['money_change_type'] == 1 ? 225:226;
                $str = '个人佣金';
                break;
            case 15://团队津贴
                $balance = $find->money_team;
                $field = 'money_team';
                $status = $post['money_change_type'] == 1 ? 227:228;
                $str = '团队津贴';
                break;
            case 16://碳票
                $balance = $find->money_vote;
                $field = 'money_vote';
                $status = $post['money_change_type'] == 1 ? 229:230;
                $str = '碳票';
                break;
            case 17://碳汇
                $balance = $find->money_converge;
                $field = 'money_converge';
                $status = $post['money_change_type'] == 1 ? 231:232;
                $str = '碳汇';
                break;
            case 18://可提现余额
                $balance = $find->money_approve;
                $field = 'money_approve';
                $status = $post['money_change_type'] == 1 ? 235:236;
                $str = '可提现余额';
                break;
            default://冻结金额
                $balance = $find->money_freeze;
                $field = 'money_freeze';
                $status = $post['money_change_type'] == 1 ? 233:234;
                $str = '冻结金额';
                break;
        }
        $balance = floatval($balance);
        $post['change_money'] = floatval($post['change_money']);
        //money_change_type 1：增加；2：减少
        //查询用户余额是否够扣
        if ($balance < $post['change_money'] && $post['money_change_type'] != 1) return $this->failed('用户'.$str.'不足');
        //edit_money改变金额
        $edit_money = $post['money_change_type'] == 1 ? $balance + $post['change_money'] : $balance - $post['change_money'];
        $save = false;
        $arr = array();
        $arr[$field] = $edit_money;
        Db::startTrans();
        try {
            if($post['money_status'] == 90){
                $money = $post['money_change_type'] == 1 ? $post['change_money'] : 0-$post['change_money'];
                SendLog::inserts($post['uid'],$money,'官方活动',$find->user_name);
            }else if($post['money_status'] == 14 || $post['money_status'] == 15){
                $money = $post['money_change_type'] == 1 ? $post['change_money'] : 0-$post['change_money'];
                FanyongLog::log($post['uid'],4,$money,'官方活动',$find->user_name);
            }else if($post['money_status'] == 18){//可提现余额修改
                $edit_balance = $post['money_change_type'] == 1 ? $find->admin_money_approve + $post['change_money'] : $find->admin_money_approve - $post['change_money'];
                $arr['admin_money_approve'] = $edit_balance < 0 ? 0 : $edit_balance;
//                $status2 = $post['money_change_type'] == 1 ? 217:218;
//                MoneyLog::inserts(3, $status2, $post['change_money'], $find->money_balance, $edit_balance, $find->id, session('admin_user.id'), '后台调整金额个人总收益', 0);
            }
            //执行修改余额
            $UserModel = new UserModel();
            $UserModel->where('id', $find->id)->update($arr);
            MoneyLog::inserts(3, $status, $post['change_money'], $balance, $edit_money, $find->id, session('admin_user.id'), '后台调整金额'.$str, 0);
            $save = true;
            Db::commit();
        } catch (ValidateException $e) {
            Db::rollback();
            // 验证失败 输出错误信息
            return $this->failed($e->getError());
        }
        if ($save) return $this->success([]);
        return $this->failed('修改失败');
    }

    public function purchase_edit($post, $find)
    {
        if ($post['change_money'] <= 0) {
            return $this->failed('金额小于0');
        }
        //1 用户余额
        $money = 0;
        $status = 0;
        //增加
        $post['change_money'] = floatval($post['change_money']);
        $UserModel = new UserModel();
        if ($post['money_change_type'] == 1) {
            $money = $find->money_purchase + $post['change_money'];
            $status = 115;
            $edit = $UserModel->where('id', $find->id)->inc('money_purchase', $post['change_money']);
        } else { //2 减少
            $money = $find->money_purchase - $post['change_money'];
            if ($money < 0) {
                return $this->failed('用户余额不够');
            }
            $edit = $UserModel->where('id', $find->id)->dec('money_purchase', $post['change_money']);
            $status = 205;
        }

        $save = false;
        Db::startTrans();
        try {
            //执行修改余额
            $edit->update();
            MoneyLog::inserts(3, $status, $post['change_money'], $find->money_purchase, $money, $find->id, session('admin_user.id'), '官方操作可购买产品余额', 0);
            $save = true;
            Db::commit();
        } catch (ValidateException $e) {
            Db::rollback();
            // 验证失败 输出错误信息
            return $this->failed($e->getError());
        }
        if ($save) return $this->success([]);
        return $this->failed('修改失败');
    }

    /**
     * 本地用户余额修改
     * @param $post /数据
     * @param $find /模型查询数据
     * @return mixed
     */
    protected function balance_edit($post, $find)
    {

        $balance = $find->money_balance;
        //查询用户钱是否够扣
        if ($find->money_balance < $post['change_money'] && $post['money_change_type'] != 1) return $this->failed('用户钱包不够');
        //state是 1时是增加
        $find->money_balance = $post['money_change_type'] == 1 ? $find->money_balance + $post['change_money'] : $find->money_balance - $post['change_money'];
        //执行修改数据
        $save = false;
        Db::startTrans();
        try {
            $find->save();
            //写操作日志
            $status = $post['money_change_type'] == 1 ? 101 : 201;
            MoneyLog::inserts(3, $status, $post['change_money'], $balance, $find->money_balance, $find->id, session('admin_user.id'), '用户充值', 0);
            $save = true;
            Db::commit();
        } catch (ValidateException $e) {
            Db::rollback();
            // 验证失败 输出错误信息
            return $this->failed($e->getError());
        }

        if ($save) return $this->success([]);
        return $this->failed('修改失败');
    }

    /**
     * @param $post /数据
     * @param $find /模型查询数据
     * @return mixed
     * 用户冻结余额修改
     */
    protected function frozen_edit($post, $find)
    {

        $balance = $find->money_freeze;
        //查询用户冻结金额是否够扣
        if ($find->money_freeze < $post['change_money'] && $post['money_change_type'] != 1) return $this->failed('用户钱包不够');

        //state是 1时是增加
        $find->money_freeze = $post['money_change_type'] == 1 ? $find->money_freeze + $post['change_money'] : $find->money_freeze - $post['change_money'];
        //执行修改数据
        $save = false;
        Db::startTrans();
        try {
            $find->save();
            //写操作日志
            (new \app\common\model\MoneyLog())->insert([
                'create_time' => date('Y-m-d H:i:s'),
                'type' => 3,
                'status' => 101,
                'money_before' => $balance,
                'money_end' => $find->money_freeze,
                'money' => $post['change_money'],
                'uid' => $find->id,
                'market_uid' => session('admin_user.id'),
            ]);
            $save = true;
            Db::commit();
        } catch (ValidateException $e) {
            Db::rollback();
            // 验证失败 输出错误信息
            return $this->failed($e->getError());
        }

        if ($save) return $this->success([]);
        return $this->failed('修改失败');
    }

    /**
     * usdt用户余额修改
     * @param $post /数据
     * @param $find /模型查询数据
     * @return mixed
     */
    protected function balance_usdt_edit($post, $find)
    {

        $balance = $find->usdt_balance;
        //查询用户钱是否够扣
        if ($find->usdt_balance < $post['change_money'] && $post['money_change_type'] != 1) return $this->failed('用户钱包不够');

        //state是 1时是增加
        $find->usdt_balance = $post['money_change_type'] == 1 ? $find->usdt_balance + $post['change_money'] : $find->usdt_balance - $post['change_money'];
        //执行修改数据
        $save = false;
        Db::startTrans();
        try {
            $find->save();
            //写操作日志
            (new \app\common\model\MoneyLog())->insert([
                'create_time' => date('Y-m-d H:i:s'),
                'type' => 3,
                'status' => 101,
                'money_before' => $balance,
                'money_end' => $find->usdt_balance,
                'money' => $post['change_money'],
                'uid' => $find->id,
                'market_uid' => session('admin_user.id'),
                'class' => 2,
            ]);
            $save = true;
            Db::commit();
        } catch (ValidateException $e) {
            Db::rollback();
            // 验证失败 输出错误信息
            return $this->failed($e->getError());
        }

        if ($save) return $this->success([]);
        return $this->failed('修改失败');
    }

    /**
     * @param $post /数据
     * @param $find /模型查询数据
     * @return mixed
     * 用户冻结余额修改
     */
    protected function frozen_usdt_edit($post, $find)
    {

        $balance = $find->usdt_freeze;
        //查询用户冻结金额是否够扣
        if ($find->usdt_freeze < $post['change_money'] && $post['money_change_type'] != 1) return $this->failed('用户钱包不够');

        //state是 1时是增加
        $find->usdt_freeze = $post['money_change_type'] == 1 ? $find->usdt_freeze + $post['change_money'] : $find->usdt_freeze - $post['change_money'];
        //执行修改数据
        $save = false;
        Db::startTrans();
        try {
            $find->save();
            //写操作日志
            (new \app\common\model\MoneyLog())->insert([
                'create_time' => date('Y-m-d H:i:s'),
                'type' => 3,
                'status' => 101,
                'money_before' => $balance,
                'money_end' => $find->usdt_freeze,
                'money' => $post['change_money'],
                'uid' => $find->id,
                'market_uid' => session('admin_user.id'),
                'class' => 2,
            ]);
            $save = true;
            Db::commit();
        } catch (ValidateException $e) {
            Db::rollback();
            // 验证失败 输出错误信息
            return $this->failed($e->getError());
        }

        if ($save) return $this->success([]);
        return $this->failed('修改失败');
    }

    /**
     ** @param $post /数据
     * @param $find /模型查询数据
     * 用户积分修改
     */
    public function points_edit($post, $find)
    {
        $balance = $find->points;
        //查询用户冻结金额是否够扣
        if ($find->money_freeze < $post['change_money'] && $post['money_change_type'] != 1) return $this->failed('用户钱包不够');

        //state是 1时是增加
        $find->points = $post['money_change_type'] == 1 ? $find->money_freeze + $post['change_money'] : $find->money_freeze - $post['change_money'];
        //执行修改数据
        $save = false;
        Db::startTrans();
        try {
            $find->save();
            //写操作日志
            (new \app\common\model\MoneyLog())->insert([
                'create_time' => date('Y-m-d H:i:s'),
                'type' => 3,
                'status' => 301,
                'money_before' => $balance,
                'money_end' => $find->points,
                'money' => $post['change_money'],
                'uid' => $find->id,
                'market_uid' => session('admin_user.id'),
            ]);
            $save = true;
            Db::commit();
        } catch (ValidateException $e) {
            Db::rollback();
            // 验证失败 输出错误信息
            return $this->failed($e->getError());
        }

        if ($save) return $this->success([]);
        return $this->failed('修改失败');
    }

    /**
     * 排行榜
     * */
    public function ranking()
    {
        //获取缓存
        $postField = 'type,status,agents';
        $post = $this->request->only(explode(',', $postField), 'post', null);
        if (!isset($post['type'])) {
            return $this->failed('无效参数');
        }
        $map = [];
        if ($post['status'] == 0) {
            $order = 'desc';
        } else {
            $order = 'asc';
        }
        if (!empty($post['agents'])) {
            $map = ['b.market_uid' => $post['agents']];
        }
        if (isset($post['start']) && isset($post['end'])) {
            $date['start'] = $post['start'];
            $date['end'] = $post['end'];
        }

        // 增加 代理商 推广列表
        if (session('admin_user.role') == 2) $map = ['b.market_uid' => session('admin_user.id')];
        $user = new UserModel();
        $way = 0;
        if ($post['type'] == 1) {
            //邀请购买人数 100
            $res = Db::name('touzi_first_buy')->alias('a')->join('common_user b', 'a.uid = b.id', 'left')->where('a.agent_id_1', '>', 0)->where($map)->field('a.agent_id_1 as user_id,count(a.uid) as num')->group('a.agent_id_1')->order('num ' . $order . '')->limit(0, 100)->select()->toArray();
        } elseif ($post['type'] == 2) {
            //用户购买产品总金额 本都货币
            $res = Db::name('touzi_product_order')->alias('a')->join('common_user b', 'a.user_id = b.id', 'left')->where($map)->field('a.user_id,sum(buy_price_local) as num')->group('a.user_id')->order('num ' . $order . '')->limit(0, 100)->select()->toArray();
        } elseif ($post['type'] == 3) {
            //累计获得佣金总合
            $res = Db::name('common_user')->alias('b')->where($map)->field('id,user_name,phone,agent_money_total as num')->order('agent_money_total ' . $order . '')->limit(0, 100)->select()->toArray();
            $way = 1;
        } elseif ($post['type'] == 4) {
            //本地金额余额
            $res = Db::name('common_user')->alias('b')->where($map)->field('id,user_name,phone,money_balance as num')->order('money_balance ' . $order . '')->limit(0, 100)->select()->toArray();
            $way = 1;
        } elseif ($post['type'] == 5) {
            //usdt余额
            $res = Db::name('common_user')->alias('b')->where($map)->field('id,user_name,phone,usdt_balance as num')->order('usdt_balance ' . $order . '')->limit(0, 100)->select()->toArray();
            $way = 1;
        } else {
            //邀请人数
            $res = Db::name('common_user')->alias('b')->join('common_pay_money_log c', 'c.uid = b.id', 'left')->where($map)->where(['c.status' => 104])->field('b.id,b.user_name,b.phone,count(c.uid) as num')->group('c.uid')->order('num ' . $order . '')->limit(0, 100)->select()->toArray();
            $way = 1;
        }

        if ($res) {
            foreach ($res as $k => $v) {
                if ($way == 0) {
                    $res_user = $user->field('user_name,phone')->where('id', $v['user_id'])->find();
                    $res[$k]['user_name'] = $res_user['user_name'] ?? '';
                    $res[$k]['phone'] = $res_user['phone'] ?? '';
                }
                $res[$k]['sort'] = $k + 1;
            }
        }
        return $this->success($res);
    }

    /**
     *
     * @return mixed|null
     * @throws \think\db\exception\DbException
     */
    public function isRealName(){
        //过滤数据
        $postField = 'id,type';
        $post = $this->request->only(explode(',', $postField), 'post', null);
        if($post['type']!=2&&$post['type']!=3){
            return $this->failed('状态值错误');
        }
        //检测订单
        $arr = explode(',',$post['id']);
        $user = new UserModel();
        $num = $user->where('id','in',$post['id'])->count();
        if($num != count($arr)){
            return $this->failed('ID验证失败');
        }
        $result = $user->where('id','in',$post['id'])->update(['is_real_name'=>$post['type']]);
        if(!$result)return $this->failed('身份状态修改失败');
        return $this->success([]);
    }

    public function bankCard(){
        //当前页
        $page = $this->request->post('page', 1);
        //每页显示数量
        $limit = $this->request->post('limit', 10);
        $uid = $this->request->post('uid');
        if (!$uid || empty($uid)) return $this->failed('用户ID错误或不存在');
        $list = BankModel::page_list(['u_id'=>$uid],$limit,$page);
        return $this->success($list);
    }

    public function bankCardEdit(){
        $postField = 'id,name,card';
        $post = $this->request->only(explode(',', $postField), 'post', null);
        if(empty($post['id'])){
            return $this->failed('无效参数');
        }
        if(empty($post['name'])||empty($post['card'])){
            return $this->failed('缺少参数');
        }
        $result = BankModel::page_one(['id'=>$post['id']]);
        if(empty($result)){
            return $this->failed('ID错误');
        }
        $res = BankModel::where(['id'=>$post['id']])->update($post);
        if(!$res)$this->failed('修改失败');
        return $this->success([]);
    }
}