<?php

namespace app\controller;

use app\BaseController;

class Base extends BaseController
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
}