<?php

namespace app\admin\controller\product;

use app\admin\controller\Base;
use app\common\model\WaresModel;
use app\validate\WaresV;
use think\exception\ValidateException;

class Wares extends Base
{

    public function initialize()
    {
        $this->model =new WaresModel();
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    //积分商品列表
    public function index(){
        //当前页
        $page = $this->request->post('page', 1);
        //每页显示数量
        $limit = $this->request->post('limit', 10);
        //查询搜索条件
        $post =$this->request->post();
        $map =[];
        isset($post['wares_name'])&& $map[]= ['wares_name','=',$post['wares_name']];
        $order = 'sort asc';
        $list =$this->model->page_list($map,$limit,$page,$order);
        return $this->success($list);
    }


    public function add(){
        //过滤数据
        $postField = 'wares_name,wares_money,wares_spec,head_img,content,status';
        $post = $this->request->only(explode(',', $postField), 'post', null);

        try {
            validate(WaresV::class)->scene('add')->check($post);
        } catch (ValidateException $e) {
            // 验证失败 输出错误信息
            return $this->failed($e->getError());
        }

        //执行修改数据
        $post['create_time']=date('Y-m-d H:i:s');
        $post['wares_type_id']=1;
        $save = $this->model->save($post);
        if ($save) return $this->success([]);
        return $this->failed('添加失败');
    }

    public function edit(){
        //过滤数据
        $postField = 'id,wares_name,wares_money,wares_spec,head_img,content,status';
        $post = $this->request->only(explode(',', $postField), 'post', null);

        try {
            validate(WaresV::class)->scene('edit')->check($post);
        } catch (ValidateException $e) {
            // 验证失败 输出错误信息
            return $this->failed($e->getError());
        }

        //执行修改数据
        $post['create_time']=date('Y-m-d H:i:s');
        $post['wares_type_id']=1;
        if (isset($post['head_img'])){
            $post['head_img'] =str_replace(config('ToConfig.app_update.image_url'),'',$post['head_img']);
        }
        $save = $this->model->where('id',$post['id'])->save($post);
        if ($save) return $this->success([]);
        return $this->failed('添加失败');
    }

    public function del(){

    }


}