<?php

/**
 * 产品列表
 *
 * */
namespace app\admin\controller\productv2;
use app\admin\controller\Base;
use app\common\model\Goods as models;
use app\common\traites\PublicCrudTrait;
use app\validate\TouziProduct as validates;
use think\exception\ValidateException;

class Goods extends Base
{
    protected $model;
    use PublicCrudTrait;

    public function initialize()
    {
        $this->model =new models();
        parent::initialize(); // TODO: Change the autogenerated stub
    }
    /**
     *
     * 产品列表
     * */
    public function index(){
        //当前页
        $page = $this->request->post('page', 1);
        //每页显示数量
        $limit = $this->request->post('limit', 10);
        //查询搜索条件
        $post =$this->request->post();
        $map =[];
        isset($post['is_open'])&& $map[]= ['is_open','=',$post['is_open']];
        $order = 'goods_type_id asc';
        $map[]= ['del','=',0];
        $list =$this->model->page_listv2($map,$limit,$page,$order);

        return $this->success($list);
    }
    /**
     * 新增
     * */
    public function add(){
        //过滤数据
        $postField = 'level_vip,buy_num,goods_agent_1,goods_agent_2,goods_agent_3,goods_type_id,goods_name,goods_money,project_scale,day_red,period,status,red_way,warrant,head_img,bottom_img,is_examine,sort,is_coupon,progress_rate';

        $post = $this->request->only(explode(',', $postField), 'post', null);
        //验证数据
        try {
            validate(validates::class)->scene('add')->check($post);
        } catch (ValidateException $e) {
            // 验证失败 输出错误信息
            return $this->failed($e->getError());
        }
        //查询是否重复
//         $find = $this->model->where('level_id',$post['level_id'])->where('class',$post['class'])->where('del',0)->find();
//        if ($find) return $this->failed('产品等级已存在');
        //执行修改数据
        $post['create_time']=date('Y-m-d H:i:s');
        $save = $this->model->save($post);
        if ($save) return $this->success([]);
        return $this->failed('添加失败');
    }
    /**
     * 编辑
     * */
    public function edit(){
        //过滤数据
        $postField = 'level_vip,buy_num,goods_agent_1,goods_agent_2,goods_agent_3,id,goods_type_id,goods_name,goods_money,project_scale,day_red,period,status,red_way,warrant,head_img,bottom_img,is_examine,sort,is_coupon,progress_rate';

        $post = $this->request->only(explode(',', $postField), 'post', null);
        //验证数据
        try {
            validate(validates::class)->scene('edit')->check($post);
        } catch (ValidateException $e) {
            // 验证失败 输出错误信息
            return $this->failed($e->getError());
        }

        //检测
        $find = $this->model->where('id', $post['id'])->find();
        if (!$find) return $this->failed('产品不存在');
        //执行修改数据

        if (isset($post['head_img'])){
            $post['head_img'] = str_replace(config('ToConfig.app_update.image_url'),'',$post['head_img']);
        }
        if (isset($post['bottom_img'])){
            $post['bottom_img'] =str_replace(config('ToConfig.app_update.image_url'),'',$post['bottom_img']);
        }
        $save = $this->model->update($post);
        if ($save) return $this->success([]);
        return $this->failed('修改失败');
    }
    /**
     * 删除
     * */
    public function del(){
        //过滤数据
        $postField ='id';
        $post = $this->request->only(explode(',', $postField), 'post', null);
        //验证数据
        try {
            validate(validates::class)->scene('del')->check($post);
        } catch (ValidateException $e) {
            // 验证失败 输出错误信息
            return $this->failed($e->getError());
        }
        //检测
        $find = $this->model->where('id', $post['id'])->find();
        if (!$find) return $this->failed('产品不存在');

        $post['del']=1;
        //执行修改数据
        $save = $this->model->update($post);
        if ($save) return $this->success([]);
        return $this->failed('删除失败');
    }


    //获取所有产品
    public function page_value_list(){
        $list = $this->model->page_sel_list([['del','=',0]],'id desc');
        return $this->success($list);
    }
}