<?php

namespace app\controller\api;

use app\controller\Base;
use app\model\AddressModel;
use app\model\AgentPath;
use app\model\BankModel;
use app\model\FanYongModel;
use app\model\GoodsDayModel;
use app\model\GoodsOrderModel;
use app\model\MoneyLogModel;
use app\model\PayCashModel;
use app\model\SendModel;
use app\model\SysConfigModel;
use app\model\UserModel;
use app\model\UserSignModel;
use app\model\WaresOrderModel;
use app\model\KeFuModel;
use app\traits\PublicCon;
use think\facade\Db;
use think\facade\Request;
use think\facade\Filesystem;

class User extends Base
{
    public $UserInfo = '';
    use PublicCon;

    public function initialize()
    {
        $this->UserInfo = $this->request->UserInfo;
        if (empty($this->UserInfo)) {
            echo show(0, [], lang(10017));
            die;
        }
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    //用户二维码
    public function UserQrcode()
    {
        $qrcde = app()->getRootPath() . '/public/static/qrcode/' . $this->UserInfo->id . '.png';
//        if (!file_exists($qrcde)) {
        $this->generate($this->UserInfo->id, TC('tg_url') . '?code=' . $this->UserInfo->id, app()->getRootPath() . '/public/static/qrcode/logo.png');
//        }
        return show(1, [
            'qrcode' => TC('qrcode_url') . '/static/qrcode/' . $this->UserInfo->id . '.png',
            'down_qrcode' => '/static/qrcode/' . $this->UserInfo->id . '.png', 'name' => $this->UserInfo->id . '.png',
            'qr_url' => TC('tg_url') . '?code=' . $this->UserInfo->id
        ]);
    }

    //下载用户二维码
    public function ThighDownload()
    {
        $name = $this->request->get('name', '');
        if (empty($name)) {
            return show([], config('ToConfig.http_code.error'), lang(10018));
        }
        $this->generate($this->UserInfo->id, TC('tg_url') . '?uid=' . $this->UserInfo->id, app()->getRootPath() . '/public/static/qrcode/logo.png');
        $path = 'public/static/qrcode/';
        return $this->download($name, $path);
    }

    //获取用户信息
    public function Index()
    {
        $IsWhole = $this->request->param('is_whole/d', 0);//是否需要 金币信息
        if ($IsWhole <= 0) {
            return show(1, $this->UserInfo);
        }
        //重新查询用户信息
        $UserInfo = UserModel::page_one([['id', '=', $this->UserInfo->id]]);
        return show(1, $UserInfo);
    }


    //修改密码
    public function UpdatePwd()
    {
        $PastPwd = $this->request->param('past_pwd', '');//旧密码
        $pwd = $this->request->param('pwd', '');//新密码
        $upwd = $this->request->param('upwd', '');//重复密码
        $sfz = $this->request->param('sfz', '');//身份证
        $captcha = $this->request->param('captcha', '');//身份证
        if (empty($sfz)) {
            return show(0, [], lang(10019));
        }
        if (empty($PastPwd)) {
            return show(0, [], lang(10020));
        }
        if (empty($pwd)) {
            return show(0, [], lang(10021));
        }
        if (empty($upwd)) {
            return show(0, [], lang(10022));
        }

        // 验证失败
        if (empty($captcha) || !$this->captcha($captcha)) {
            return show(0, [], lang(10005));
        }

        if ($pwd != $upwd) {
            return show(0, [], lang(10004));
        }

        $UserInfo = UserModel::page_one([['id', '=', $this->UserInfo->id]]);
        if ($sfz != $UserInfo['sfz']) {
            return show(0, [], lang(10023));
        }

        $gpwd = $UserInfo->getData('pwd');

        if ($gpwd != md5($PastPwd)) {
            return show(0, [], lang(10024));
        }
        UserModel::where([['id', '=', $this->UserInfo->id]])->update(['pwd' => md5($pwd)]);
        return show(1);
    }

    //我的团队
    public function UserTeam()
    {
        $lv = $this->request->param('lv/d', 1);
        if ($lv <= 0) {
            return show(0, lang(10025));
        }
        list($page, $limit) = $this->mapSel();

        //我的推荐人信息
        $AgentInfo = [];
        //下一级信息
        $belowAgentInfo = [];
        //已经购买的人数
        //查询自己的上一级
        if ($this->UserInfo->agent_id > 0) {
            $AgentInfo = UserModel::page_one([['id', '=', $this->UserInfo->agent_id]], 'user_name,phone,id,head_img');
        }

        switch ($lv) {
            case 0:
            case 1:
                //自己的信息 第一级
                $belowAgentInfo = $this->UserInfo;
                //查询自己是否有购买产品
                break;
            case 2:
                //查询自己下一级信息 第二级
                $belowAgentInfo = UserModel::page_sel([['agent_id', '=', $this->UserInfo->agent_id]], 'user_name,phone,id,head_img', $page, $limit);
                break;
            case 3:
                //查询自己下一级信息 第三级
                $belowAgentInfo = UserModel::page_sel([['agent_id_2', '=', $this->UserInfo->agent_id]], 'user_name,phone,id,head_img', $page, $limit);
                break;
            case 4:
                //查询自己下一级信息 第四级
                $belowAgentInfo = UserModel::page_sel([['agent_id_3', '=', $this->UserInfo->agent_id]], 'user_name,phone,id,head_img', $page, $limit);
                break;
        }

        //1 查询下级ID
        $ArrayColumnId = UserModel::below_agent($lv, $this->UserInfo->id);

        $buyer = GoodsOrderModel::buyerCount($ArrayColumnId);//查询下级购买人数

        return show(1, ['agent_info' => $AgentInfo, 'below_agent_info' => $belowAgentInfo, 'buyer' => $buyer]);
    }

    //根据用户ID查询用户的下一级
    public function UserListTeam()
    {
        $uid = $this->request->param('uid/d', 0);
        if ($uid <= 0) {
            return show(0);
        }
        //查询用户下一级
        list($page, $limit) = $this->mapSel();
        $belowAgentInfo = UserModel::page_sel([['agent_id', '=', $uid]], 'user_name,phone,id,head_img', $page, $limit);
        return show(1, $belowAgentInfo);
    }

    //查询团队指定用户
    public function UserOneTeam()
    {
        $name = $this->request->param('user_name', '');
        if (empty($name)) {
            return show(0);
        }

        //查询用户是否存在
        $find = UserModel::page_one([['user_name', '=', $name], ['agent_id_1|agent_id_2|agent_id_3', '=', $this->UserInfo->id]], 'id,user_name,head_img,agent_id_1,agent_id_2,agent_id_3');
        if (empty($find)) {
            return show(0);
        }
        $lv = 0;
        if ($find['agent_id_1'] == $this->UserInfo->id) {
            $lv = 1;
        } elseif ($find['agent_id_2'] == $this->UserInfo->id) {
            $lv = 2;
        } elseif ($find['agent_id_3'] == $this->UserInfo->id) {
            $lv = 3;
        }
        $find['lv'] = $lv;
        //查询用户是否是我的下一级
        return show(1, $find);
    }

    //收益
    public function Income()
    {
//        $map = [
//            ['is_send', '=', 1],
//            ['user_id', '=', $this->UserInfo->id],
//        ];
//        // 1 每日收益
//        $sum = SendModel::toDayMoney($map);

        //1 获取用户的所有订单
        $map = [
            ['status', 'in', [1,0]],
            ['uid', '=', $this->UserInfo->id],
            ['surplus_red_day', '>', 0]
        ];
        $sum = 0;
        $List = GoodsOrderModel::PageSel($map);
        if (empty($List)) {
            return show(1, ['today' => $sum]);
        }

        foreach ($List as $key => $value) {
            //2 获取 每个天数每天能够获得的金额
            $GoodsDay = [];
            $GoodsDay = GoodsDayModel::where('id', $value['day_id'])->cache(100)->find();
            if (empty($GoodsDay)) {
                continue;
            }
            $sum += $GoodsDay['income'] * $value['order_number'];
        }

        //2 总分红在个人资料
        return show(1, ['today' => $sum]);
    }

    //投注记录
    public function Invest()
    {
        list($page, $limit, $time) = $this->mapDateSel();
        $map = [
            ['uid', '=', $this->UserInfo->id],
            ['status', '>=', 0],
        ];

        $list = GoodsOrderModel::orderLog($map, $time, $page, $limit)->toArray();
        $CountMoney = GoodsOrderModel::countMoney($map, $time);
        $list['count_money'] = $CountMoney;
        return show(1, $list);
    }

    //收益记录
    public function LogIncome()
    {
        list($page, $limit, $time) = $this->mapDateSel();
        $map = [
            ['user_id', '=', $this->UserInfo->id],
            ['is_send', '=', 1],
        ];
        $list = SendModel::orderLog($map, $time, $page, $limit)->toArray();
        $CountMoney = SendModel::countMoney($map, $time);
        $list['count_money'] = $CountMoney;
        return show(1, $list);
    }

    //提现记录
    public function Withdrawal()
    {
        list($page, $limit, $time) = $this->mapDateSel();
        $type = $this->request->param('type',1);
        $map = array();
        $map[] = ['u_id', '=', $this->UserInfo->id];
        $map[] = ['pay_type','=',$type];
        $list = PayCashModel::orderLog($map, $time, $page, $limit)->toArray();
        $map[] = ['status', '=', 1];
        $CountMoney = PayCashModel::countMoney($map, $time);
        $list['count_money'] = $CountMoney;
        return show(1, $list);
    }


    //提现申请记录
    public function WithdrawalApplication()
    {
        list($page, $limit, $time) = $this->mapDateSel();
        $map = [
            ['u_id', '=', $this->UserInfo->id],
            ['status', '=', 0],
        ];
        $list = PayCashModel::orderLog($map, $time, $page, $limit);
        return show(1, $list);
    }

    //收货地址
    public function address()
    {
        $UserName = $this->request->post('user_name', '');
        $phone = $this->request->post('phone', '');
        $province = $this->request->post('province', '');
        $city = $this->request->post('city', '');
        $county = $this->request->post('county', '');
        $address = $this->request->post('address', '');
        $default = $this->request->post('default', 0);
        if (empty($UserName)) {
            return show(0, [], lang(10026));
        }
        if (empty($phone)) {
            return show(0, [], lang(10027));
        }
        if (empty($province)) {
            return show(0, [], lang(10028));
        }
        if (empty($city)) {
            return show(0, [], lang(10029));
        }
        if (empty($county)) {
            return show(0, [], lang(10030));
        }
        if (empty($address)) {
            return show(0, [], lang(10031));
        }
        //不能重复添加地址
        $where = array();
        $where['province'] = $province;
        $where['city'] = $city;
        $where['county'] = $county;
        $where['address'] = $address;
        $res = AddressModel::where($where)->find();
        if ($res) {
            return show(0, lang(10032), lang(10032));
        }
        //选择默认地址的时候，把其他的都设置为不默认地址
        if ($default > 0) {
            AddressModel::where(['uid' => $this->UserInfo->id])->update(['is_default' => 0]);
        }

        AddressModel::insets([
            'uid' => $this->UserInfo->id,
            'is_default' => $default,
            'username' => $UserName,
            'phone' => $phone,
            'province' => $province,
            'city' => $city,
            'county' => $county,
            'address' => $address,
            'create_time' => date('Y-m-d H:i:s'),
            'update_time' => date('Y-m-d H:i:s'),
        ]);
        return show(1);
    }

    //我的收货地址
    public function MyAddress()
    {
        //我的默认收获地址
        $default = $this->request->get('default', 0);
        $map = [];
        $map[] = ['uid', '=', $this->UserInfo->id];
        if ($default > 0) {
            $map[] = ['is_default', '=', 1];
        }
        $list = AddressModel::where($map)->select();
        return show(1, $list);
    }

    public function EditAddress()
    {
        $UserName = $this->request->post('user_name', '');
        $phone = $this->request->post('phone', '');
        $province = $this->request->post('province', '');
        $city = $this->request->post('city', '');
        $county = $this->request->post('county', '');
        $address = $this->request->post('address', '');
        $default = $this->request->post('default', 0);

        if (empty($UserName)) {
            return show(0, [], lang(10026));
        }
        if (empty($phone)) {
            return show(0, [], lang(10027));
        }
        if (empty($province)) {
            return show(0, [], lang(10028));
        }
        if (empty($city)) {
            return show(0, [], lang(10029));
        }
        if (empty($county)) {
            return show(0, [], lang(10030));
        }
        if (empty($address)) {
            return show(0, [], lang(10031));
        }
        $aid = $this->request->post('aid/d', 0);
        if ($aid <= 0) {
            return show(0, [], lang(10033));
        }
        //选择默认地址的时候，把其他的都设置为不默认地址
        if ($default > 0) {
            AddressModel::where(['uid' => $this->UserInfo->id])->update(['is_default' => 0]);
        }
        AddressModel::where(['id' => $aid, 'uid' => $this->UserInfo->id])->update([
            'is_default' => $default,
            'username' => $UserName,
            'phone' => $phone,
            'province' => $province,
            'city' => $city,
            'county' => $county,
            'address' => $address,
            'create_time' => date('Y-m-d H:i:s'),
            'update_time' => date('Y-m-d H:i:s'),
        ]);
        return show(1);
    }

    public function DelAddress()
    {
        $aid = $this->request->post('aid/d', 0);
        if ($aid <= 0) {
            return show(0, [], lang(10034));
        }
        $find = AddressModel::where(['uid' => $this->UserInfo->id, 'id' => $aid])->find();
        if (empty($find)) {
            return show(0, [], lang(10035));
        }

        $del = AddressModel::where(['uid' => $this->UserInfo->id, 'id' => $aid])->delete();
        if ($del) {
            show(1);
        }
        show(0);
    }

    //我的银行卡列表
    public function MyBank()
    {
        $list = BankModel::page_list([['u_id', '=', $this->UserInfo->id]]);
        return show(1, $list);
    }

    //用户绑定提现密码
    public function WithdrawPwd()
    {
        $pwd = $this->request->post('pwd', '');
        $sfz = $this->request->post('sfz', '');
        $captcha = $this->request->post('captcha', '');
        if (empty($pwd) || empty($sfz) || $pwd < 4) {
            return show(0, [], lang(10036));
        }

        if ($pwd == 123456 || strlen($pwd) != 6){
            return show(0, [], lang(10037));
        }
        // 验证失败
        if (empty($captcha)) {
            // if (empty($captcha) || !$this->captcha($captcha)) {
            return show(0, [], lang(10005));
        }

        if ($this->UserInfo->sfz != $sfz) {
            return show(0, [], lang(10038));
        }
        UserModel::where('id', $this->UserInfo->id)->update(['withdraw_pwd' => base64_encode($pwd)]);
        return show(1);
    }

    //银行卡绑定
    public function bank()
    {
        $name = $this->request->post('name', '');
        $card = $this->request->post('card', '');
        $AccountName = $this->request->post('account_name', '');
        $default = $this->request->post('default', 0);

        if (empty($name)) {
            return show(0, [], lang(10039));
        }
        if (empty($card)) {
            return show(0, [], lang(10027));
        }
        if (empty($AccountName)) {
            return show(0, [], lang(10028));
        }
        $where = array();
        $where['id'] = $this->UserInfo->id;
        $res = UserModel::page_one($where);
        if ($res['user_name'] != $AccountName) {
            return show(0, [], lang(10040));
        }
        if (BankModel::where('card', $card)->find()) {
            return show(0, [], lang(10041));
        }
        if ($default > 0) {
            BankModel::where(['u_id' => $this->UserInfo->id])->update(['is_default' => 0]);
        }

        BankModel::insets([
            'u_id' => $this->UserInfo->id,
            'is_default' => $default,
            'status' => 1,
            'account_name' => $AccountName,
            'card' => $card,
            'name' => $name,
        ]);
        return show(1);
    }

    public function EditBank()
    {
        $name = $this->request->post('name', '');
        $card = $this->request->post('card', '');
        $AccountName = $this->request->post('account_name', '');
        $default = $this->request->post('default', 0);

        if (empty($name)) {
            return show(0, [], lang(10039));
        }
        if (empty($card)) {
            return show(0, [], lang(10027));
        }
        if (empty($AccountName)) {
            return show(0, [], lang(10028));
        }

        $bid = $this->request->post('bid/d', 0);
        if ($bid <= 0) {
            return show(0, [], lang(10042));
        }
        if (BankModel::where('card', $card)->where('id', '<>', $bid)->find()) {
            return show(0, [], lang(10041));
        }

        $where = array();
        $where['id'] = $this->UserInfo->id;
        $res = UserModel::page_one($where);
        if ($res['user_name'] != $AccountName) {
            return show(0, [], lang(10043));
        }

        if ($default > 0) {
            BankModel::where(['u_id' => $this->UserInfo->id])->update(['is_default' => 0]);
        }

        BankModel::where(['id' => $bid, 'u_id' => $this->UserInfo->id])->update([
            'is_default' => $default,
            'status' => 1,
            'account_name' => $AccountName,
            'card' => $card,
            'name' => $name,
        ]);
        return show(1);
    }

    public function DelBank()
    {
        $bid = $this->request->post('bid/d', 0);
        if ($bid <= 0) {
            return show(0, [], lang(10044));
        }
        $find = BankModel::where(['u_id' => $this->UserInfo->id, 'id' => $bid])->find();
        if (empty($find)) {
            return show(0, [], lang(10045));
        }

        $del = BankModel::where(['u_id' => $this->UserInfo->id, 'id' => $bid])->delete();

        if ($del) {
            return show(1);
        }
        return show(0);
    }

    //我的积分商品订单
    public function MyWaresOrder()
    {
        list($page, $limit) = $this->mapSel();
        $map = [
            ['uid', '=', $this->UserInfo->id],
        ];
        //

        $list = WaresOrderModel::page_list($map, $limit, $page, 'id desc');
        return show(1, $list);
    }


    //提现操作
    public function WithdrawalAdd()
    {
        $money = $this->request->post('money', 0);
        $u_bank_name = $this->request->post('u_bank_name', '');
        $u_back_card = $this->request->post('u_back_card', '');
        $u_back_user_name = $this->request->post('u_back_user_name', '');
        $pwd = $this->request->post('pwd', '');

        if ($money <= 0 || empty($u_bank_name) || empty($u_back_card) || empty($u_back_user_name) || empty($pwd)) {
            return show(0, [], lang(10046));
        }

        if($pwd == 123456){
            return show(0, [], lang(10001));
        }

        $withdrawal_start = SysConfigModel::page_value([['name', '=', 'withdrawal_start']]);//提现最少金额
        if ($money <$withdrawal_start ){
            return show(0, [], sprintf(lang(10056), $withdrawal_start));
        }


        $UserInfo = UserModel::page_one([['id', '=', $this->UserInfo->id]]);

        if ($UserInfo['is_real_name'] != 2) {
            return show(0, [], lang(10047));
        }
        if ($UserInfo->getData('withdraw_pwd') != base64_encode($pwd)) {
            return show(0, [], lang(10048));
        }

        if ($UserInfo['money_approve'] < $money) {
            return show(0, [], lang(10049));
        }

        $commission = SysConfigModel::page_value([['name', '=', 'withdrawal_commission']]);//提现手续

        $CommissionMoney = $money * $commission / 100;//手续费
        $ActualMoney = $money - $CommissionMoney;//实际到账

        $text = '';
        $residue = 0;//用户收益扣除金额
        $activity = 0;//用户活动扣除金额
        $activity_end = 0;//用户剩余活动金额
        $balance_end = 0;//用户收益剩余金额;
        Db::startTrans();
        try {
            //1 插入提现表
            $PayCashId = PayCashModel::inserts([
                'create_time' => date('Y-m-d H:i:s'),
                'money' => $money,
                'money_before' => $UserInfo['money_balance'],
                'money_end' => $UserInfo['money_balance'] - $money,
                'money_fee' => $CommissionMoney,
                'money_actual' => $ActualMoney,
                'msg' => '用户申请提现。可提现余额：' . $UserInfo['money_approve'] . ",结束：" . ($UserInfo['money_approve'] - $money),
                'u_id' => $this->UserInfo->id,
                'u_ip' => $this->request->ip(),
                'status' => 0,
                'pay_type' => 1,
                'u_bank_name' => $u_bank_name,
                'u_back_card' => $u_back_card,
                'u_back_user_name' => $u_back_user_name,
                'market_uid' => $this->UserInfo->market_uid,
                'order_on' => orderCode()
            ]);
            //2 修改用户余额和冻结金额
            $text = '用户提现'.$money.'元';
            $model = UserModel::where('id', $this->UserInfo->id)->dec('money_approve', $money);
            if($money <= $UserInfo['admin_money_approve']){
                $model->dec('admin_money_approve', $money);
                $activity = $money;
                $activity_end = $UserInfo['admin_money_approve'] - $money;
            }elseif ($UserInfo['admin_money_approve'] > 0){
                $model->dec('admin_money_approve', $UserInfo['admin_money_approve']);
                $residue = $money - $UserInfo['admin_money_approve'];
                $activity = $UserInfo['admin_money_approve'];
            }else{
                $residue = $money;
            }
            if($residue > 0){
                if($UserInfo['money_balance'] >= $residue){
                    $model->dec('money_balance', $residue);
                    $balance_end = $UserInfo['money_balance'] - $residue;
                    $text1 = $text.',收益扣除'.$residue.'元。';
                }else if($UserInfo['money_balance'] > 0){
                    $model->dec('money_balance', $UserInfo['money_balance']);
                    $residue = $UserInfo['money_balance'];
                    $text1 = $text.'，可提现金额足够，收益不足，允许提现，收益扣除'.$residue.'元。';
                }else{
                    $text1 = $text.'，可提现金额足够，收益为0，允许提现。';
                }
                //用户收益记录
                SendModel::insert([
                    'user_id' => $UserInfo['id'],
                    'product_id' => 0,
                    'product_order_id' => 0,
                    'user_name' => $UserInfo['user_name'],
                    'product_title' => '用户提现',
                    'create_time' => date('Y-m-d H:i:s'),
                    'send_time' => date('Y-m-d H:i:s'),
                    'is_send' => 1,
                    'send_money' => 0 - $residue,
                ]);
                //写入资金记录
                MoneyLogModel::inserts(2, 201, $UserInfo['money_balance'], $balance_end, $residue, $this->UserInfo->id, $this->UserInfo->market_uid, $text1, $PayCashId);
            }
            if($activity > 0){
                $text2 = $text.'，活动金额扣除'.$activity.'元。';
                //活动金额记录
                MoneyLogModel::inserts(2, 209, $UserInfo['admin_money_approve'], $activity_end, $activity, $this->UserInfo->id, $this->UserInfo->market_uid, $text2, $PayCashId);
            }
            $model->inc('money_freeze', $money)->inc('total_withdraw', $money)->update();

            //可提现金额写入资金记录
            MoneyLogModel::inserts(2, 216, $UserInfo['money_approve'], $UserInfo['money_approve'] - $money, $money, $this->UserInfo->id, $this->UserInfo->market_uid, $text, $PayCashId);
            Db::commit();
        } catch (\Exception $e) {
            // 回滚事务
            Db::rollback();
            return show(0, [], $e->getMessage());
        }
        return show(1);
    }

    //团队提现
    public function TeamWithdrawalAdd()
    {
        $money = $this->request->post('money', 0);
        $u_bank_name = $this->request->post('u_bank_name', '');
        $u_back_card = $this->request->post('u_back_card', '');
        $u_back_user_name = $this->request->post('u_back_user_name', '');
        $pwd = $this->request->post('pwd', '');


        if ($money <= 0 || empty($u_bank_name) || empty($u_back_card) || empty($u_back_user_name)) {
            return show(0, [], lang(10046));
        }

        $UserInfo = UserModel::page_one([['id', '=', $this->UserInfo->id]]);

        if ($UserInfo->getData('withdraw_pwd') != base64_encode($pwd)) {
            return show(0, [], lang(10048));
        }

        if ($UserInfo['is_real_name'] != 2) {
            return show(0, [], lang(10047));
        }

        $withdrawal_start = SysConfigModel::page_value([['name', '=', 'withdrawal_start']]);//提现最少金额
        if ($money <$withdrawal_start ){
            return show(0, [], sprintf(lang(10056), $withdrawal_start));
        }

//        if ($UserInfo['money_approve'] <= 0) {
//            return show(0, [], '用户可提现资格不足');
//        }
        if ($UserInfo['money_hire']  < $money) {
            return show(0, [], lang(10050));
        }

        $commission = SysConfigModel::page_value([['name', '=', 'withdrawal_commission']]);//提现手续

        $CommissionMoney = $money * $commission / 100;//手续费
        $ActualMoney = $money - $CommissionMoney;//实际到账
        $money_name = 'money_hire';
        Db::startTrans();
        try {
            //用户增加减少返佣余额
            Db::name('common_user')->where('id',$this->UserInfo->id)->dec($money_name,$money)->update();
            $msg = '用户团队提现';
            //2 插入提现表
            $PayCashId = PayCashModel::inserts([
                'create_time' => date('Y-m-d H:i:s'),
                'money' => $money,
                'money_before' => $UserInfo[$money_name],
                'money_end' => $UserInfo[$money_name]-$money,
                'money_fee' => $CommissionMoney,
                'money_actual' => $ActualMoney,
                'msg' => $msg,
                'u_id' => $this->UserInfo->id,
                'u_ip' => $this->request->ip(),
                'status' => 0,
                'pay_type'=>2,
                'u_bank_name' => $u_bank_name,
                'u_back_card' => $u_back_card,
                'u_back_user_name' => $u_back_user_name,
                'market_uid' => $this->UserInfo->market_uid,
                'order_on' => orderCode()
            ]);
            //3 写入资金记录
            MoneyLogModel::inserts(2, 202, $UserInfo[$money_name], $UserInfo[$money_name]-$money, $money, $this->UserInfo->id, $this->UserInfo->market_uid, $msg . 'ID:' . $PayCashId, $PayCashId);
            Db::commit();
        } catch (\Exception $e) {
            // 回滚事务
            Db::rollback();
            return show(0, [], $e->getMessage());
        }
        return show(1);
    }

    //充值操作
    public function RechargeAdd()
    {
        //
    }

    //用户签到
    public function sign()
    {
        $UserInfo = UserModel::page_one([['id', '=', $this->UserInfo->id]]);

        //签到赠送积分数量
        $money = SysConfigModel::page_value([['name', '=', 'give_money_integral']]);//积分;
        $save = UserSignModel::sign($UserInfo, $money);

        if ($save) {
            return show(1);
        }
        return show(0, [], lang(10051));
    }

    public function MySign()
    {
        //我的签到时间
        $list = UserSignModel::month_list([['uid', '=', $this->UserInfo->id]]);
        $data = [];
        if (!empty($list)) {
            foreach ($list as $key => $value) {
                $data[] = date('Y-m-d', strtotime($value));

            }
        }
        return show(1, $data);
    }

    //客服
    public function customer()
    {
        $one = Db::query("SELECT * FROM `ntp_common_kefu` ORDER BY RAND() limit 1");
        return show(1, $one);
    }


    //返佣记录
    public function rebate()
    {
        list($page, $limit) = $this->mapSel();

        $time = $this->request->param('time', '');
        $map = [
            ['user_id', '=', $this->UserInfo->id],
            ['is_add_to_user_account', '=', 1],
        ];
        $list = FanYongModel::month_list_two($map, $time, $limit, $page)->toArray();
        $list['count_money'] = FanYongModel::countMoney($map, $time);
        return show(1, $list);
    }


    //用户头像上传
    public function UploadImages()
    {
        // 获取上传的图片文件
        $image = $this->request->file();

        if (empty($image)) {
            return show(0, [], lang(10052));
        }
        // 验证文件并移动到指定目录
        try {
            validate(['image' => ['fileSize:2048000', 'fileExt:jpg,jpeg,png']])
                ->check(['image' => $image]);

            foreach ($image as $im) {
                $savename = Filesystem::disk('touxiang')->putFile('touxiang', $im);
                break;
                // $savename[] = \think\facade\Filesystem::putFile('topic', $file);
            }

            //$savename = Filesystem::disk('touxiang')->putFile('touxiang', $image);
            $image_url = '/static/' . str_replace('\\', '/', $savename);

            // 将上传的图片信息保存到数据库
            $result = UserModel::where('id', $this->UserInfo->id)->update(['head_img' => $image_url]);

            if (!$result) {
                return show(0);
            }
            return show(1);
        } catch (\Exception $e) {
            return show(0, [], $e->getMessage());
        }
    }

    //查询用户指定下级购买的情况
    public function UserGoodsList()
    {
        $uid = $this->request->param('uid/d', 0);
        if ($uid <= $this->UserInfo->id) {
            return show(0);
        }
        $map = [
            ['uid', '=', $uid],
        ];
        list($page, $limit) = $this->mapSel();
        //查询用户的购买情况
        $list = GoodsOrderModel::orderLog($map, '', $page, $limit)->toArray();
        $CountMoney = GoodsOrderModel::countMoney($map, '');
        $list['count_money'] = $CountMoney;
        return show(1, $list);
    }

    //查询用户下级人数
    public function UserSubordinate()
    {
//        $count = UserModel::where('agent_id_1|agent_id_2|agent_id_3', $this->UserInfo->id)->count();

        //查询我的下级用户有那些
        $array1 = AgentPath::where('path','LIKE', "%{$this->UserInfo->id}|%")->where('uid','<>',$this->UserInfo->id)->column('uid');
        $count = count($array1);
        if (empty($array1)){
            return show(1, ['subordinate' => $count, 'purchased' => 0]);
        }

        //查询购买了 产品的用户
        $array2 = GoodsOrderModel::where('uid','in',$array1)->where('goods_type_id','<>',3)->group('uid')->column('uid');
        // 找到两个数组的交集
        $result = array_intersect($array1, $array2);
        // 重新索引
        $result = array_values($result);
        $ren = count($result);
        return show(1, ['subordinate' => $count, 'purchased' => $ren]);
    }

    //查询用户碳票，积分，碳汇，绿币
    public function MoneyLogList()
    {
        $type = $this->request->get('type/d', 0);
        $status = [];
        switch ($type) {
            case 1:
                $status = MoneyLogModel::$integral;
                break;//积分
            case 2:
                $status = MoneyLogModel::$green;
                break;//绿币
            case 3:
                $status = MoneyLogModel::$vote;
                break;//碳票
            case 4:
                $status = MoneyLogModel::$converge;
                break;//碳汇
            default:
                $type = 0;
                break;
        }

        if ($type <= 0) {
            return show(0);
        }
        list($page, $limit, $time) = $this->mapDateSel();

        $map = [
            ['uid', '=', $this->UserInfo->id],
            ['status', 'in', $status],
        ];
        //类型
        $list = MoneyLogModel::month_list($map, $time, $limit, $page);
        if($type == 1) {
            $user = UserModel::page_one([['id', '=' ,$this->UserInfo->id]], 'money_integral');
            $list['count_money'] = $user['money_integral'];
        }else{
            $CountMoney = MoneyLogModel::countMoney($map, $time);
            $list['count_money'] = $CountMoney;
        }
        return show(1, $list);
    }

    /**
     * 获取专属客服ID
     * @return false|string|\think\response\Json
     */
    public function C_service()
    {
        if (!$this->UserInfo->id) {
            return show(0, [], lang(10053));
        }

        if ($this->UserInfo->market_uid) {
            return show(1, ['market_uid' => $this->UserInfo->market_uid]);
        }
        $keFu = new KeFuModel();
        $res = $keFu->randomId();
        return show(1, ['market_uid' => $res->id]);
    }

    /**
     * 获取用户头像
     * @return false|string|\think\response\Json
     */
    public function sculpture(){
        if (!$this->UserInfo->id) {
            return show(0, [], lang(10053));
        }
        $arr = array();
        for($i=1;$i<=20;$i++){
            $data = array();
            $data['url'] = TC('touxiang_url').'/static/touxiang/'.$i.'.png';
            $data['image'] = '/static/touxiang/'.$i.'.png';
            $arr[] = $data;
        }
        return show(1, $arr);
    }

    /**
     * 用户头像修改
     * @return false|string|\think\response\Json
     */
    public function headEdit(){
        $head_img = $this->request->post('head_img', '');
        if (empty($head_img)) {
            return show(0, [], lang(10054));
        }
        // 将上传的图片信息保存到数据库
        $result = UserModel::where('id', $this->UserInfo->id)->update(['head_img' => $head_img]);

        if (!$result) {
            return show(0, lang(10055));
        }
        return show(1);
    }
}
