<?php

namespace app\model;

use think\Model;

class BaseModel extends Model
{
    public static $imageUrl = '';
    public static function init()
    {
        self::$imageUrl = TC('image_url');
        parent::init(); // TODO: Change the autogenerated stub
    }
}