<?php


namespace app\admin\controller\log;


use app\admin\controller\Base;


use app\common\model\PayCash as models;
use app\common\model\UserModel;
use app\common\pay\CarryOrderv1;
use app\common\pay\CarryOrderv2;
use app\common\service\Excel;
use app\common\traites\PublicCrudTrait;
use app\model\SendModel;
use think\exception\ValidateException;
use think\facade\Db;
use think\facade\Log;
use app\common\model\SysConfig;
use app\common\model\MoneyLog;

class PayCash extends Base
{
    protected $model;
    use PublicCrudTrait;

    const TYPE_WITHDRAWAL_REFUND = 4; //提现退款
    const STATUS_WITHDRAWAL_REFUSAL = 237;  //拒绝提款
    const STATUS_WITHDRAWAL_TEAM_REFUSAL = 238;//团队提现拒绝
    const AUDIT_WITHDRAWAL_REFUND = 2;        //提现被拒绝

    /**
     * 提现控制器
     */
    public function initialize()
    {
        $this->model = new models();
        //  parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 列表
     */
    public function index()
    {
        //当前页
        $page = $this->request->param('page', 1);
        //每页显示数量
        $limit = $this->request->param('limit', 20);
        $is_excel = $this->request->param('is_excel', 0);

        $ids = $this->request->param('ids');

        //查询搜索条件
        $post = $this->request->param();
        $map = [];
        $date = [];
        isset($post['user_name']) && $map [] = ['b.user_name|b.phone', 'like', '%' . $post['user_name'] . '%'];
        isset($post['status']) && $post['status'] != '' && $map [] = ['a.status', '=', intval($post['status'])];
        isset($post['type']) && $map [] = ['a.type', '=', intval($post['type'])];
        isset($post['agents']) && $post['agents'] != '' && $map[] = ['b.market_uid', '=', $post['agents']];
        isset($post['uid']) && $post['uid'] != '' && $map[] = ['a.u_id', '=', $post['uid']];
        isset($post['order_on']) && $post['order_on'] != '' && $map[] = ['a.order_on', '=', $post['order_on']];
        isset($post['pay_type']) && $post['pay_type'] != '' && $map[] = ['a.pay_type', '=', $post['pay_type']];
        if (isset($post['start']) && isset($post['end'])) {
            $date['start'] = $post['start'];
            $date['end'] = $post['end'];
        }

        $list = $this->model->page_list($map, $limit, $page, $date);

        if ($is_excel > 0) {
            $map = [];
            if ($ids == '') {
                $ids = '0';
            }
            $ids = explode(',', $ids);
            $map[] = ['a.id', 'in', $ids];

            $list = $this->model->page_list($map, count($ids), 1, []);
            $list = $list->toArray();
            if (!empty($list['data'])) {
                $this->excel($list['data']);
            }
        }
        return $this->success($list);
    }


    public function pass()
    {
        //过滤数据
        $postField = 'id';
        $post = $this->request->only(explode(',', $postField), 'post', null);
        //检测订单
        $find = $this->model->where('id', $post['id'])->where('status', 0)->find();
        if (!$find) return $this->failed('该提现订单已处理或不存在');
        if ($find['is_status'] == 1) return $this->failed('已经提交了');
        $find = $find->toArray();
        //拉起代付
        $SysConfig = new SysConfig();
        $is_pay_v = $SysConfig->where('name', 'is_carry_v')->value('value');

        if ($is_pay_v == 2) {
            $CarryOrderv1 = new CarryOrderv2();
//            $res = $CarryOrderv1->createOrder($find['money_actual'],['order_on'=>$find['order_on']],$find['u_bank_card'],$find['u_bank_user_name'],$find['ifsc'],'');数据库返回u_back_card 而非u_bank_card //2023-05-31
            $res = $CarryOrderv1->createOrder($find['money_actual'], ['order_on' => $find['order_on']], $find['u_back_card'], $find['u_back_user_name'], '', '');

            if (empty($res)) {
                return $this->failed('失败');
            }
            $res = json_decode($res, true);
            if (isset($res['success']) && $res['success'] == true) {
                //修改当前订单状态
                $this->model->where('id', $post['id'])->update(['is_status' => 1]);
                return $this->success($res);
            } else {
                return $this->failed($res['msg']);
            }
        } else {
            $CarryOrderv2 = new CarryOrderv1();

//            $res = $CarryOrderv2->createOrder($find['money_actual'],['order_on'=>$find['order_on']],$find['u_bank_card'],$find['u_bank_user_name'],$find['ifsc'],''); 数据库返回u_back_card 而非u_bank_card //2023-05-31
            /*没有支付暂时关闭
            $res = $CarryOrderv2->createOrder($find['money_actual'],['order_on'=>$find['order_on']], $find['u_back_card'], $find['u_back_user_name'], '','');

            if(empty($res)){
                return $this->failed('失败');
            }

            $res = json_decode($res,true);
            if (isset($res['success']) && $res['success'] == true){
                $this->model->where('id',$post['id'])->update(['is_status'=>1]);
                return $this->success($res);
            }else{
                return $this->failed($res['msg']);
            }
            */


//            $this->model->where('id',$post['id'])->update(['is_status'=>1]);
            $this->model->where('id', $post['id'])->update(['status' => 1]);
            $mUser = new UserModel();
            $mUser->add_total_withdraw($find['u_id'], $find['money']);
            return $this->success('');
        }

        die;
        foreach ($find as $k => $v) {
            Db::startTrans();
            try {
                //提现 清除冻结 改变状态
                if ($v['type'] == 1) {
                    // Db::name('common_user')->where('id',$data['uid'])->dec('money_freeze',$data['money'])->update();
                    Db::name('common_user')->where('id', $v['uid'])->inc('money_total_withdraw', $v['money_actual'])->update();
                    //记录
                    // \app\common\model\MoneyLog::flowing(1,2,1,201,$user,$data['money'],$data['id'],'同意提现本地货币冻结资金释放');
                } else {
                    //  Db::name('common_user')->where('id',$data['uid'])->dec('usdt_freeze',$data['money'])->update();
                    Db::name('common_user')->where('id', $v['uid'])->inc('usdt_total_withdraw', $v['money_actual'])->update();
                    //记录
                    // \app\common\model\MoneyLog::flowing(1,2,2,201,$user,$data['money'],$data['id'],'同意提现USDT冻结资金释放');
                }
                $data['status'] = 1;
                $data['success_time'] = date('Y-m-d H:i:s');
                $data['admin_uid'] = session('admin_user')['id'];
                //执行修改数据
                $this->model->where('id', $v['id'])->save($data);
                Db::commit();
            } catch (ValidateException $e) {
                Db::rollback();
                // 验证失败 输出错误信息
                \think\facade\Log::write('批量提现通过错误id：' . $v['id'] . '，错误信息：' . json_encode($e->getMessage()), 'notice');
                continue;
            }
        }
        return $this->success([]);
    }
    /**
     * 通过
     * */
//    public function pass(){
//        //过滤数据
//        $postField = 'id';
//        $post = $this->request->only(explode(',', $postField), 'post', null);
//        //检测订单
//        $find = $this->model->where('id','in',$post['id'])->where('status',0)->select()->toArray();
//        if (!$find) return $this->failed('该提现订单已处理或不存在');
//        foreach ($find as $k=>$v){
//            Db::startTrans();
//            try {
//                //提现 清除冻结 改变状态
//                if ($v['type']==1){
//                    // Db::name('common_user')->where('id',$data['uid'])->dec('money_freeze',$data['money'])->update();
//                    Db::name('common_user')->where('id',$v['uid'])->inc('money_total_withdraw',$v['money_actual'])->update();
//                    //记录
//                    // \app\common\model\MoneyLog::flowing(1,2,1,201,$user,$data['money'],$data['id'],'同意提现本地货币冻结资金释放');
//                }else{
//                    //  Db::name('common_user')->where('id',$data['uid'])->dec('usdt_freeze',$data['money'])->update();
//                    Db::name('common_user')->where('id',$v['uid'])->inc('usdt_total_withdraw',$v['money_actual'])->update();
//                    //记录
//                    // \app\common\model\MoneyLog::flowing(1,2,2,201,$user,$data['money'],$data['id'],'同意提现USDT冻结资金释放');
//                }
//                $data['status']=1;
//                $data['success_time']=date('Y-m-d H:i:s');
//                $data['admin_uid']= session('admin_user')['id'];
//                //执行修改数据
//                $this->model->where('id',$v['id'])->save($data);
//                Db::commit();
//            } catch (ValidateException $e) {
//                Db::rollback();
//                // 验证失败 输出错误信息
//                   \think\facade\Log::write('批量提现通过错误id：'.$v['id'].'，错误信息：'.json_encode($e->getMessage()),'notice');
//                continue;
//            }
//        }
//        return $this->success([]);
//    }
    /**
     *
     * 线上还是线下打款
     * */
    public function is_line()
    {
        //过滤数据
        $postField = 'id,is_online';
        $post = $this->request->only(explode(',', $postField), 'post', null);
        //检测订单
        $find = $this->model->where('id', (int)$post['id'])->where('status', 1)->where('is_online', 0)->find();
        // 执行线上打款接口 开始 应老板需求新增

        $post['line_time'] = date('Y-m-d H:i:s');
        $post['line_admin_uid'] = session('admin_user')['id'];
        $post['is_online'] = $post['is_online'] == 1 ? 1 : 2;

        if ($post['is_online'] == 1) {
            $cashOrderInfo = $find->toArray();
            $this->daifu($cashOrderInfo);
            // 更新 状态
            $res = $this->model->update($post);
            if ($res) {
                return $this->success([]);
            } else {
                return $this->failed('线上打开失败');
            }

        } else {
            $res = $this->model->update($post);
            if ($res) {
                return $this->success([]);
            } else {
                return $this->failed('线下打开失败');
            }
        }
    }

    /**
     * 提现记录
     * */
    public function daifu($info)
    {
        $SysConfig = new SysConfig();

        //支付地址
        $api_address = $SysConfig->where('name', 'admin_address')->value('value');
        //前端地址
        $web_address = $SysConfig->where('name', 'web_address')->value('value');
        $daifuData = array();
        $daifuData['merchant'] = '88006';
        $daifuData['total_amount'] = $info['money_actual']; // Number
        $daifuData['callback_url'] = $api_address . '/home/back/daiFuBack';
        $daifuData['order_id'] = $info['order_on'];
        $daifuData['bank'] = $info['u_bank_name'];
        $daifuData['bank_card_name'] = $info['u_bank_user_name'];
        $daifuData['bank_card_account'] = $info['u_bank_card']; // Number
        $daifuData['bank_card_remark'] = 'no';
        $daifuData['sign'] = verifySignApplet($daifuData);

        $url = 'https://apicloud.gcash.cash/api/daifu';
        $curl_res = curl_post($url, $daifuData);
        Log::write('代付信息：' . $curl_res, 'notice');
        if ($curl_res) {
            $curls_res = json_decode($curl_res, true);
            if ($curls_res['status'] == 1) {
                //  return show(json_encode($curls_res['message']),1);
            } else {
                return $this->failed(json_encode($curls_res['message']));
            }
        } else {
            return show([], config('ToConfig.http_code.error'), 'Invalid payment link');
        }
    }

    /**
     *
     * 拒绝
     * */
    public function refuse()
    {
        //过滤数据
        $postField = 'id,msg';
        $post = $this->request->only(explode(',', $postField), 'post', null);
        //检测订单
        $find = $this->model->where('id',  $post['id'])->where('status', 0)->find();
        if (!$find) return $this->failed('该提现订单已处理或不存在');

        $mUser = new UserModel();
        $mMoneyLog = new MoneyLog();
        $userInfo = $mUser->info($find['u_id']);//查询用户信息
        $money_before = 0;
        $money_end = 0;
        $market_uid = $userInfo->market_uid;
        $money =  $find['money'];
        $type = self::TYPE_WITHDRAWAL_REFUND;
        if ($find['pay_type'] == 1){
            $status = self::STATUS_WITHDRAWAL_REFUSAL;
            $money_before = $userInfo['money_approve'];
            $money_end = $userInfo['money_approve'] + $money;
            $mark = '用户提现未通过审核，返还提现金额';
            $product_title = '用户提现未通过审核，返还可提现金额';
            //增加用户可提现金额
            $mUser->where('id',$find['u_id'])->dec('money_freeze',$money)->dec('total_withdraw',$money)->inc('money_approve',$money)->update();
        }elseif ($find['pay_type'] == 2){
            $status = self::STATUS_WITHDRAWAL_TEAM_REFUSAL;
            $money_before = $userInfo['money_hire'];
            $money_end = $userInfo['money_hire'] + $money;
            $mark = '用户提现未通过审核，返还团队金额';
            $product_title = '用户提现未通过审核，返还团队金额';
            $mUser->where('id',$find['u_id'])->inc('money_hire',$money)->update();
        }
        //1 退回用户金额
        $mMoneyLog->inserts($type, $status, $money, $money_before, $money_end, $find['u_id'], $market_uid, $mark, $find['id']);
        $this->model->where('id', $find['id'])->save(['status' => self::AUDIT_WITHDRAWAL_REFUND]);

        return $this->success([]);
    }

    /**
     * 修改金额
     * */
    public function amount_edit()
    {
        //过滤数据
        $postField = 'id,money_fee,money_actual';
        $post = $this->request->only(explode(',', $postField), 'post', null);
        //检测订单
        $find = $this->model->where('id', $post['id'])->where('status', 0)->find();
        if (!$find) return $this->failed('该提现订单已处理或不存在');
        if ((!isset($post['money_fee']) && !is_numeric($post['money_fee'])) || (!isset($post['money_actual']) && !is_numeric($post['money_actual']))) {
            return $this->failed('请传递有效参数');
        }
        $res = $this->model->update($post);
        if ($res) {
            return $this->success([]);
        } else {
            return $this->failed('操作失败');
        }
    }


    private function excel($data)
    {
        $excel = new Excel();

        $field_title = [
//            'id'=>'ID',
//            'create_time'=>'申请时间',
//            'success_time'=>'审核时间',
            'money' => '提现金额',
//            'money_before'=>'开始金额',
//            'money_end'=>'结束金额',
//            'money_fee'=>'手续费',
//            'money_actual'=>'实际到账金额',
//            'order_on'=>'订单号',
//            'phone'=>'电话',
            'user_name' => '姓名',
//            'u_bank_name'=>'银行名',
            'u_back_card' => '收款账号',
            'u_back_user_name' => '收款名',
//            'msg'=>'备注',
        ];

        $fields = [
//            'id',
//            'create_time',
//            'success_time',
//            'success_time',
            'money',
//            'money_before',
//            'money_end',
//            'money_fee',
//            'money_actual',
//            'order_on',
//            'phone',
            'user_name',
//            'u_bank_name',
            'u_back_card',
            'u_back_user_name',
//            'msg'
        ];
        $filename = '提现导出' . date('YmdHis');
        return $excel->export($field_title, $fields, $data, $filename);
    }

}